.gitignore
pom.xml
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-lattice/pom.xml
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-lattice/src/main/java/org/springframework/cloud/data/module/deployer/lattice/ReceptorModuleDeployer.java
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-lattice/src/main/java/org/springframework/cloud/data/module/deployer/lattice/ReceptorModuleInstanceStatus.java
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-spi/pom.xml
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-spi/src/main/java/org/springframework/cloud/data/module/ModuleInstanceStatus.java
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-spi/src/main/java/org/springframework/cloud/data/module/ModuleStatus.java
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-spi/src/main/java/org/springframework/cloud/data/module/deployer/ModuleDeployer.java

Includes
- Dependencies on Receptor API and Spring XD modules
- .gitignore updates for Eclipse and IntelliJ
- Scaffolding for Lattice/Receptor implementations
Reviewers - **please double check my work with regard to the Maven dependencies**. I tried to place the dependency on XD modules in the top level POM but could not get it to work. Maven only fetched the dependencies when I placed them in the child-level POMs.

Initial commit of SPI interfaces

---

pom.xml
spring-cloud-data-module-registry/src/main/java/org/springframework/cloud/data/module/registry/StubModuleRegistry.java
spring-cloud-data-rest/pom.xml
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/repository/StreamDefinitionRepository.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/repository/StubStreamDefinitionRepository.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/AdminApplication.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/StreamController.java

The purpose of this PR is to provide the initial foundation for the spring-cloud-data REST API, including the way the StreamController will interact with the StreamDefinitionRepository, ModuleRegistry, and ModuleDeployer.
This includes (temporary) stub implementations of the ModuleRegistry and StreamDefinitionRepository. The ModuleRegistry interface was updated since we need to pass type information in addition to the name of a module. That type will be necessary for mapping to the proper ModuleCoordinates. It will also allow us to continue using names such as "file" in both the source and sink position of a stream definition.
The StreamController functions for an end-to-end PoC, but it will be replaced with a version that @pperalta has been working on, and at that point it will be …

initial commit for spring-cloud-data-rest

---

spring-cloud-data-rest/pom.xml
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/AdminApplication.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/config/AdminConfiguration.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/controller/StreamController.java

Currently this will create a ReceptorModuleDeployer bean if the "cloud" profile is active,
a LocalModuleDeployer, otherwise. We will later enhance this to be more fine-grained,
including support for a CloudFoundry ModuleDeployer implementation.

initial commit for profile-driven ModuleDeployer

---

spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/data/module/deployer/cloudfoundry/CloudFoundryModuleDeployer.java
spring-cloud-data-rest/pom.xml
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/config/AdminConfiguration.java

if the "cloud" and "lattice" profiles are both active, the LatticeModuleDeployer bean is instantiated
if the "cloud" profile is active but "lattice" is not, the CloudFoundryModuleDeployer bean is instantiated
if the "cloud" profile is not active, the LocalModuleDeployer bean is instantiated
also added a stub implementation of CloudFoundryModuleDeployer

profile-driven ModuleDeployer beans

---

spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-local/src/main/java/org/springframework/cloud/data/module/deployer/local/LocalModuleDeployer.java
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-local/src/main/java/org/springframework/cloud/data/module/deployer/local/LocalModuleInstanceStatus.java

simply returns "deployed" if it has deployed a module, but "unknown" otherwise
will evolve once we decide how we'll interact with running modules (and once we have `undeploy()` implemented)

initial local module status

---

spring-cloud-data-shell/src/main/java/org/springframework/cloud/data/shell/command/Assertions.java
spring-cloud-data-shell/src/test/java/org/springframework/cloud/data/shell/command/AssertionsTests.java

swapped these two exception types based on the following rationale:
- IllegalArgumentException means that the input is *invalid* and thus we can't even continue with the assertion
- IllegalStateException means the assertion itself failed (the data does not conform to the required state)
also added comprehensive unit tests

switch IllegalState and IllegalArg for Assertions

---

spring-cloud-data-rest/pom.xml
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/controller/AdminController.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/controller/SecurityController.java
spring-cloud-data-rest/src/main/resources/application.yml

- Port minimal configurations required to setup admin UI
- This change currently uses `spring-xd-ui` artifact explicitly
- The inclusion of `SecurityController` is unavoidable since the
XD admin UI client mandates the check on security controller info
Use spring-xd-admin-ui-client directly
Fix admin info request mapping

Setup Admin UI

---

pom.xml
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-lattice/pom.xml

- This way the `spring-cloud-lattice-core`, `spring-cloud-lattice-connector` and
`receptor-client` versions can be management centrally

Add `spring-cloud-lattice` into dependencyManagement

---

spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-lattice/src/main/java/org/springframework/cloud/data/module/deployer/lattice/LrpModuleDeployer.java

- When deploying `s-c-s-module-launcher` docker image as LRP, the explicit `cloud` profile
need not be set as it needs to be auto activated by the module's lattice core dependency

Remove explicit `cloud` profile for LRP request

---

README.md
spring-cloud-data-admin/pom.xml
spring-cloud-data-admin/src/main/resources/application.yml
spring-cloud-data-yarn/pom.xml
spring-cloud-data-yarn/spring-cloud-data-yarn-appmaster/pom.xml
spring-cloud-data-yarn/spring-cloud-data-yarn-appmaster/src/main/resources/application.yml
spring-cloud-data-yarn/spring-cloud-data-yarn-client/pom.xml
spring-cloud-data-yarn/spring-cloud-data-yarn-client/src/main/resources/application.yml
spring-cloud-data-yarn/spring-cloud-data-yarn-client/src/main/resources/log4j.properties
spring-cloud-data-yarn/spring-cloud-data-yarn-container/src/main/resources/application.yml

NOTE: check README for changes howto start admin and client
- Modify build to replace placeholder `@project.version@` with
a proper version which is needed for other than snapshots.
- Generic polish of yml files
- Moved logging config into application.yml for client. Somehow
this boot logging got broken again without doing any changes.
- Introduce `clouddata.yarn.app.appmaster.path` and
`clouddata.yarn.app.container.path` which defaults to `.` and can be
used to define actual locations where appmaster and container jars
will be found. Defaults to `.` because it is assumed that with an actual
release all needed jars are in a same location.
- Updated README

XD-3461 Remove yarn related hardcoded file paths

---

spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/CloudFoundryApplicationTemplate.java
spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/ModuleStatusBuilder.java

Currently only STARTED is recognized and interpreted as module state
`deployed`. This commit recognizes all the application instance states
we are aware of, and interprets them as various module instance states.
It also attempts to obtain application instance status irrespective of
the reported state of the application, and ignores the exception that
might be thrown.

Interpret more application states

---

spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/ModuleStatusBuilder.java

If a deployment fails on CloudFoundry the resulting apps may be in the
"DOWN" state. This state was not allowed for in the calculation of
module status, which meant that the module status was classed as 'unknown'.
Modules in that status are not undeployed, hence the apps were orphaned
on CF. This change adds the missing state, allowing such modules to be
deleted as expected.

Destroy Failed Deploys

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/BindingProperties.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/ModuleDefinitionBuilder.java

- Support inputType/outputType for the module (same support that Spring XD has)
- Set the module parameters as s-c-s binding properties based on the inputType/outputType specified in DSL

Add type conversion support

---

spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-local/src/main/java/org/springframework/cloud/dataflow/module/deployer/local/LocalModuleDeployer.java

- The spring-cloud-dataflow banner gets displayed when the local module deployer deploys the modules. We need to disable showing the dataflow banner for the modules.

Don't show banner for local module deployer

---

spring-cloud-dataflow-admin/src/main/java/org/springframework/cloud/dataflow/admin/config/ArtifactRegistryPopulator.java

Will need to `FLUSHDB` your redis to remove all keys.

Use 'exec' as the default qualifier when registering modules

---

spring-cloud-dataflow-yarn/spring-cloud-dataflow-yarn-container/src/main/java/org/springframework/cloud/dataflow/yarn/container/ContainerApplication.java

If we perform some "expensive" operations during creation a parameters for logger's methods (as concatenation of strings), to perform isInfoEnabled() check - is a good practise.

Add isInfoEnabled() for logging operations

---

spring-cloud-dataflow-module-deployer-spi/pom.xml

- use `dataflow-parent` instead of `deployers-parent` which no longer exists.

Fix module-deployers-spi parent

---

spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/CompletionConfiguration.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ExpandOneDashToTwoDashesRecoveryStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/StreamCompletionProvider.java
spring-cloud-dataflow-completion/src/test/java/org/springframework/cloud/dataflow/completion/StreamCompletionProviderTests.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/CheckPointedParseException.java

Fixes spring-cloud/spring-cloud-dataflow#262
I made the configuration order explicit, and got rid of the circular
dependency at the cost of duplicating a bit of logic found in
StreamCompletionProvider in ExpandOneDashToTwoDashesRecoveryStrategy.

Make sure closed set value provider runs last

---

spring-cloud-dataflow-admin-local/src/main/java/org/springframework/cloud/dataflow/admin/spi/local/LocalDeployerAutoConfiguration.java
spring-cloud-dataflow-admin-local/src/main/java/org/springframework/cloud/dataflow/admin/spi/local/OutOfProcessModuleDeployerProperties.java
spring-cloud-dataflow-admin-local/src/main/resources/META-INF/spring.factories
spring-cloud-dataflow-admin-local/src/test/java/org/springframework/cloud/dataflow/admin/spi/local/LocalConfigurationTests.java

- Since the auto configuration class will be enabled as long as the `local` jar path is in the classpath, make this auto configuration class
conditional only if the class `ModuleDeployer` is also present
- Rename `LocalAutoConfiguration` to `LocalDeployerAutoConfiguration` as `local` looks more generic when used in the context of other application
This resolves #356

Fix in-process deployer

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java

- When the app deployment property `count` is set, then set the property `spring.cloud.deployer.count` and pass it as environment property for the app definition
This resolves #464

Set spring cloud deployer count property when count is set

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

- Add missing use of DeploymentIdRepository in a
TaskDefinitionController when querying task
status from a TaskLauncher.
- Fixes #512

Use persisted id for task status

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java

- Fix import to use correct class `org.springframework.cloud.deployer.spi.app.DeploymentState`
instead of `org.springframework.cloud.dataflow.module.DeploymentState` which
caused undeploy attempt every time.
- Fixes #521

Fix DeploymentState import

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeModulesController.java

- Fix RuntimeModulesController to use deployment id
so that `runtime modules` command wont fail with
deployers expecting correct format when status
is queried.
- Generic polish, javadocs, sts warnings.
- Fixes #544

RuntimeModulesController using deployment id

---

spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/CompletionConfiguration.java
spring-cloud-dataflow-configuration-metadata/pom.xml
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/stream/configuration/metadata/ClassloaderUtils.java
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/stream/configuration/metadata/ModuleJarLauncher.java
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-registry/pom.xml
spring-cloud-starter-dataflow-server-local/pom.xml

- Remove spring-cloud-dataflow-app-launcher and bring
back missing stuff needed for metadata.
- spring-cloud-dataflow-dependencies remove project.version
- spring-cloud-dataflow-registry, spring-cloud-starter-dataflow-server-local
and spring-cloud-starter-dataflow-server-local remove hardcoded version.
- Fixes #570

Fix pom versions

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

I followed the docs to tease out tapping the `task-events`; however, without the binder dependency, we would get the following exception while launching the task/batch.
```
RELEASE.jar!/:4.2.5.RELEASE]
... 39 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.stream.binder.BinderTypeRegistry]: Factory method 'binderTypeRegistry' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Cannot create binder factory, no `META-INF/spring.binders` resources found on the classpath
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at …
```

Update docs to include binder dependency

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/CounterControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/FieldValueCounterControllerTests.java

- Add RedisTestSupport to skip redis dependent tests if redis is not available
This resolves #799

Check Redis availability for tests

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/security/SecurityController.java

- Since the `SecurityProperties` is set at the constructor level via controller auto configuration, we don't need `EnableConfigurationProperties` for `SecurityProperties` at
SecurityController
This fixes #366

Remove EnableConfig prop at SecurityController

---

spring-cloud-dataflow-shell/pom.xml

with this PR people can just run the shell using `./spring-cloud-dataflow-shell.jar` (as opposed to `java -jar spring-cloud-dataflow-shell.jar`). They can still _also_ use `java -jar ..`, of course. It's just nice not to have to. This uses a feature in Spring Boot's Maven plugin introduced in 1.3.

make the shell executable

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/CounterControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/FieldValueCounterControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/RedisDeploymentIdRepositoryTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/RedisStreamDefinitionRepositoryTests.java
spring-cloud-dataflow-test-support/pom.xml
spring-cloud-dataflow-test-support/src/main/java/org/springframework/cloud/dataflow/test/AbstractExternalResourceTestSupport.java
spring-cloud-dataflow-test-support/src/main/java/org/springframework/cloud/dataflow/test/RedisTestSupport.java

Fixes spring-cloud/spring-cloud-dataflow#849
This will ease migrating SCDF to boot 1.4, as boot upgrades its spring-data version

Remove dependency on scs-test-support-internal

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml

- Move external dependencies out of `spring-cloud-dataflow-dependencies` BOM and to `spring-cloud-dataflow` parent
- Fix BOM only to have dataflow project dependencies
- Use `project.version` wherever appropriate
Resolves #976

Fix spring-cloud-dataflow-dependencies BOM

---

pom.xml

- Use different build properties for deployer spi and
local versions as those have a different lifecycle.
- Fixes #985

Separate deployer build versions

---

pom.xml

* Add additional plugin versions to avoid maven project warnings
Fixes #988

Reference Spring Cloud Release train directly vs. individual jars

---

spring-cloud-dataflow-docs/src/main/asciidoc/architecture.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

- Also some additional changes
1.  Removing getting started doc change for disabling security for http
2.  Removing duplicated content of using YAML for the deployment properties
Resolves #1182

Update existing docs using the new 'deployer' prefix

---

spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/AppRegistry.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java
spring-cloud-dataflow-server-core/src/test/resources/META-INF/test-apps-overwrite.properties

- When overwrite is set to true, the existingKey collection should be empty so that all the apps get registered and if `overwrite` is false the collection would return the non-empty collection so that only those apps that have unavailable keys get registered
Resolves #1195

Fix app importAll overwrite

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/job/support/DeploymentPropertiesUtilsTests.java

- Move away from regex in favor of simple
comma splitting.
- As comma split will produce wrong key/value
pairs if values itself are comma delimited list,
go through split and combine to previous candidate
if parsed key/value doesn't look like it is
key/value.
- Fixes #1235

Overhaul deployment properties parsing

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeTemplate.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsControllerTests.java

- list method now understand Pageable.
- modified stream handling to only return current page
- modified RuntimeTemplate to request 10000 items which is
a same value what StreamTemplate is using. For some
reason Pageable defaults to size 20 so shell need to request
more to get past 20 items is shell doesn't use paging.
- fixes #1251
- this also is a root cause for spring-cloud/spring-cloud-dataflow-ui#176

Add paging to RuntimeAppController

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java

- When the step executions are retrieved for the composed job, since we have a new step name for the steps inside the batch jobs of the composed task everytime a step is executed for the batch job, the `getStepExecutions(Long jobExecutionId)` returns all the step executions that are distinct. This causes the step executions of all the batch jobs executed under the name of the composed task.
- To fix this, look for non-null step executions for each step execution added to the job execution
Resolves #1241

Fix composed task's job step executions

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/graph/Graph.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/TaskParserTests.java

Fixes https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/197
With this change if you quote wildcards in the DSL box they will get unquoted when the graph is built and if you leave them unquoted in the graph building, they will get quoted when the DSL is built - as expected by composed-task-runner. This will need revisiting when we think about how to handle exit codes (vs exit statuses).

Ensure consistency with quoted wildcard handling for composed tasks

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-migration-guide.adoc

Remove ':' from the channel names in the router config in example

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ResourceBasedAuthorizationInterceptor.java

The Apache HTTP client doesn't recognize invalid characters (such as
`\r\n`) in header values. This commit explictly trims white space
eliminating common causes of this problem.

Trim whitespace from external credentials

---

spring-cloud-dataflow-docs/src/main/asciidoc/applications.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/shell.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

- Resolve app registration link from index.adoc instead of streams.adoc (fixes the problem of other servers not able to resolve the cross-links)
- Fix composed task shell formatting issues
- Add "nowrap" option for extended table samples (a scroll bar comes up now)
Resolves spring-cloud/spring-cloud-dataflow#1607
Resolves spring-cloud/spring-cloud-dataflow#1591

Address various doc formatting issues

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

- Spring Boot 1.5.7
- Spring Cloud Dalston.SR3
- also setting deployer version to 1.3.0.BUILD-SNAPSHOT
Resolves #1649

Updating versions for Spring Boot and Spring Cloud

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

- Add logout-success-oauth.html to permitted pages.
- Fixes #1659

Fix access to oauth logout notify page

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfigurationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/TestUtils.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithLdapSearchAndBindSslTests.java

- In favour of letting skipper to create its client
modify DataFlowControllerAutoConfiguration to import
SkipperClientConfiguration and move skipperStreamDeployer
into nested config class.
- With this mod we get same RestTemplate as used in
skipper shell which works better for exception handling
related to errors thrown via rest layer.
- Modify some existing tests and add new one to ensure
SkipperClientProperties are processed into new
SkipperClient.
- Also ignore ssl tests which turned out to be unreliable.
- Fixes #1713
- Fixes #1764

Use SkipperClient from skipper

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/CheckableResource.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ProcessOutputResource.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ResourceBasedAuthorizationInterceptor.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/resource/HttpClientTest.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java

If a command specified using --dataflow.credentials-provider-command fails and
returns a non-zero exit status code, an exception is thrown to simplify problem diagnosis.
Before this was implemented, any output of the failed command was used as an authentication header, resulting in an obscure HTTP 4xx error.
Resolves spring-cloud/spring-cloud-dataflow#1775.

Diagnose credentials provider command failure

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithSingleUserTests.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithUsersFileTests.java

- Assign VIEW role for the Skipper GET REST endpoints under `/streams/deployments`
- Update tests
Resolves #1814

Authenticate Skipper GET endpoints

---

spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/AbstractAppRegistryCommon.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/AppRegistry.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/service/AppRegistryService.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/service/DefaultAppRegistryService.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/ResourceUtils.java
spring-cloud-dataflow-registry/src/test/java/org/springframework/cloud/dataflow/registry/support/ResourceUtilsTests.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/VersionedAppRegistryController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java

- Instead of invoking `getResource` via the underlying LRUCleaningResourceLoader, construct the resource based on the schemes used in the URI
- For maven resource, parse the co-ordinates and construct MavenResource with the appropriate MavenProperties (configured in the server)
- Make sure to inject the maven properties
- Remove `getResource` from AppRegistryService as we no longer need to download the resource at the registry
- Use DefaultResourceLoader in AppRegistry for the use case where the `--uri` option is used to download the http resource when `registerAll`
- The delegating resource loader is now used only when downloading the metadata resource at the AppRegistry
- Add tests for resource version retrieval
Resolves #1843

Retrieve app version without downloading

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AboutController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/common/ConfigCommands.java

Resolves #1921
- RuntimeEnvironmentInfo based on Skipper version and platform list
- Remove UnsupportedOperationException throwing/catching
- The shell info-commands table shows Skipper Deployer instead of App Deployer in Skipper mode

RuntimeEnvironmentInfo for Skipper mode

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java

- If the stream has at least one of the apps successfully deployed but at least one of the apps has failed, then the aggregate state needs to be set to `partital` instead of `failed`
- This state will show the appropriate status description as:
`In the case of multiple apps, some have successfully deployed, while others have not`
Resolves #1974

Fix partial aggregate deployment state

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AboutControllerTests.java

- Make sure to have suffix `Tests` to be included in the surefire test report
Resolves #2022

Fix test class name suffix

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/support/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceIntegrationTests-upgradeWithSensitivePropertiesManifest.yml

Resolves #1985
- Extend ArgumentSanitizer to handle key,value properties
- Add tests for the ArgumentSanitizer and for the DefaultSkipperStreamService
- Resolution is applied to Skipper mode only.

Stream DSL - sanitize sensitive properties

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java

Without this fix the endpoint for finding related streams
will stackoverflow for one or more streams that refer
to each other. Streams like this are bad/incorrect but
they shouldn't cause the server to break. This simple change
simply avoids recursing multiple times into the same stream
def.
Fixes #2150

Avoid stackoverflow when asking server for related streams

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/support/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java

Resolves #2196
for 1.5.0 branch
- Parse/process Stream's DSL using the java API (e.g. StreamDefinition, StreamAppDefinition) instead of incomplete regular expressions.
- Fix the affected tests

Incorrect Stream properties sanitizing

---

pom.xml

**PORT ONTO MASTER BRANCH AS WELL**
We were managing the dependency to 1.2.2 when it should be whatever spring cloud common security config requires.
Note, the version of spring-session pulled in for the local server is managed by spring-boot-parent. The 1.2.2 dep was getting pulled into the final jar on the PCF/k8s servers.

Remove explicit mgmt of spring-session

---

spring-cloud-dataflow-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/job/support/DeploymentPropertiesUtilsTests.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

 - Allow passing comma characters into Task's launch arguments list
- Fixes Doc's tests for
Resolves #1826
(back ported from commits 955901b and 0393634)

Support comma chars in Task argument values

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

This proposal adds `app default` (PUT) endpoint to the default security role mapping. 
I've verified the change with the following config/example (in skipper mode):
configs:
```
security.basic.enabled=true
security.user.name=test
security.user.password=pass
security.user.role=VIEW,CREATE,MANAGE
```
before this change:
```
dataflow:>app default --id source:http --version 2.0.0.BUILD-SNAPSHOT
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Access is denied
```
after this change:
```
dataflow:>app list --id source:http
╔═════════════════════════════╤═════════╤════╤════╗
║           source            │processor│sink│task║
╠═════════════════════════════╪═════════╪════╪════╣
║> http-2.0.0.BUILD-SNAPSHOT <│         │    │    ║
║http-1.3.1.RELEASE …
```

Include "app default" endpoint in security role mapping

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2292

gh-2292 Fix: Don't query for latest task executions when no task definitions are present

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

This was added as a part of configuration options, but also really needs to be in the split execution section as well.
resolves #2313

Added docs for CTR thread count req for splits

---

spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/samples.adoc
spring-cloud-dataflow-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskSchedulerDocumentation.java
spring-cloud-dataflow-docs/src/test/resources/org/springframework/restdocs/templates/asciidoctor/path-parameters.snippet

* Updated samples adoc to remove the ERROR reported by api-guide.adoc.  Basically samples.adoc structure was incorrect causing api-guide to be out of the formal structure of the docs.
* Reset the sections in the schedules document
* There is a bug in Spring Restdocs that caused the WARNING: skipping reference to missing attribute: XYZ.  Andy Wilkinson gave us a template to resolve those warnings and has opened an issue in Restdocs to resolve the problem.  https://github.com/spring-projects/spring-restdocs/issues/527
* Using the doc build there are no error or warnings that popup, however there are still 2 that popup when I do the CI Plan build, but no followup information on where they can be sourced to.
resolves #2233

Updated asciidocs to remove warnings

---

spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolver.java
spring-cloud-dataflow-configuration-metadata/src/test/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolverTests.java
spring-cloud-dataflow-configuration-metadata/src/test/resources/org/springframework/cloud/dataflow/configuration/metadata/apps/deprecated-error/META-INF/spring-configuration-metadata.json

- In case property is manually set to error level in
deprecation field, simply skip returning it, effectively
not showing it anywhere.
- Fixes #2357

Skip error deprecated properties

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/DSLMessage.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/DestinationNode.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/StreamParser.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/TokenKind.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/Tokenizer.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/NodeTests.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/StreamParserTests.java

This adds support in the parser/tokenizer to allow stream destination
names to include slash(/), star(*) or hash(#). Extra tests added and
minor refactoring (simplification) to DestinationNode.
Fixes #2425 
Fixes #2430

Add support for wildcards in stream destination names

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AppDeploymentRequestCreator.java

- The stream update properties goes through the whitelist properties qualification only when there are properties to handle.
Resolves #2586

Conditionally qualify the update properties

---

spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Now example shows multi-binder transformer and specifies that user creates it.  Prevents confusion.
Some bug fixes and version updates
resolves #2572

Updates the multi-binder example

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Docs now state that tasks used in split should not set exit message

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java

- Group beans into AppRegistryConfiguration, TaskEnabledConfiguration, StreamEnabledConfiguration, AuditingConfiguration, SecurityConfiguration and MetricsConfiguration configuration inner classes
- Common beans are left at top level
Followup of #2596
Resolves #2633

Re-structure DataFlowControllerAutoConfiguration

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceTests.java
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceIntegrationTests-rollbackManifest.yml
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceTests-rollbackManifest.yml

- Change the rollback method to return rolledback release
- Use RollbackRequest instead of deprecated one
- Update the stream DSL after the rollback is complete
- Add test for update after rollback
- Fix rollbackStream service test
- Fix NPE on release during rollback
Resolves #2636

[1.7.x] Update Stream DSL after rollback

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

- As postgres driver we use doesn't support PgConnection.createClob(),
during a startup exception is thrown on INFO level basically just
for notification, silence this by changing log level for that
class to WARN.
- github.com/spring-cloud/spring-cloud-dataflow/issues/2750 has links
to github.com/pgjdbc/pgjdbc/issues/1102 with more discussion about
this.
- Fixes #2750

Silence hibernate clob error with postgres

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/db2/Db2BeforeBaseline.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/db2/V1__Initial_Setup.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mysql/MysqlBeforeBaseline.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mysql/V1__Initial_Setup.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/oracle/OracleBeforeBaseline.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/oracle/V1__Initial_Setup.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/postgresql/PostgresBeforeBaseline.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/postgresql/V1__Initial_Setup.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/sqlserver/MsSqlBeforeBaseline.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/sqlserver/V1__Initial_Setup.java

- As newly modified scripts are only valid for mysql and
essentially broken for postgres, db2, oracle and sqlserver
add missing references to all *BeforeBaseline#createBatchTables()
functions.
- Also fix all V1__Inital_Setup#CREATE_TASK_DEFINITIONS_TABLE scripts
to have a correct format for each databases which needs to follow
what SchemaGenerationTests creates as you can't just create one for
mysql and copy those over to other db's.
- Generic polish for sql's.
- Fixes #2816

Fix flyway scripts for new task_deployment table

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-registry/pom.xml
spring-cloud-dataflow-server-core/pom.xml

- Remove explicit hikari version as it's managed by boot which
brings in 3.2.0 instead of 3.1.0 we've been hardcoding.
- As we use newer maria version than boot manages, define
it in spring-cloud-dataflow-dependencies using same
property version name as boot uses.
- This now allows a custom build to use just
spring-cloud-starter-dataflow-server-local and
spring-cloud-dataflow-dependencies
- Fixes #2845

Polish dependencies

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-howto.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc

I attempted to fix the export-commands that aren't bash friendly by having them as env-vars in a property file. 
I verified the change locally by starting the server pointing to a CF environment. I had confirmed it with a successful start along with the properties loaded up as a map at: http://localhost:9393/management/configprops.
Resolves #2858

Fix docs to run server locally against a remote CF environment

---

spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTemplate.java

While running locally the task execution id was 1. But in CI we have pre-existing task launches.
To resolve this, the test was updated to retrieve a task execution list for a unique test name.  And then the execution id is extracted.
This extracted execution id is then used to determine success

Resolves problem with testTaskLaunch

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityWithUsersFileTests.java

* Add rule to `dataflow-server-defaults.yml`
* Add tests to `LocalServerSecurityWithUsersFileTests`
resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2963

gh-2963 Fix Security: URI `/tasks/platforms` not covered

---

spring-cloud-dataflow-docs/src/main/asciidoc/applications.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Following incorrect references were corrected.
1) Fix duplicate rows for "bridge" and "aggregator"
2) Add missing apps ("pmml", "counter", "tasklauncher-dataflow")
3) Add deprecations where applicable
There were a few references to Clark train and that's fixed now.
Finally, also, I flipped Elston from RC1 to GA albeit the release is not done yet. Elston is waiting on SCDF 2.0 (CTR 2.1 GA depends on SCDF 2.0 GA) -> 🐔 or 🥚? When we release SCDF 2.0, it'd be better not to have RC1 references.

Fix incorrect application references

---

mvnw
mvnw.cmd
pom.xml
spring-cloud-dataflow-completion/src/test/support/boot13/pom.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://stackoverflow.com/questions/18107375/getting-skipping-jacoco-execution-due-to-missing-execution-data-file-upon-exec migrated to:  
https://stackoverflow.com/questions/18107375/getting-skipping-jacoco-execution-due-to-missing-execution-data-file-upon-exec ([https](https://stackoverflow.com/questions/18107375/getting-skipping-jacoco-execution-due-to-missing-execution-data-file-upon-exec) result 200).
* http://www.apache.org/licenses/LICENSE-2.0 migrated to: …

URL Cleanup

---

spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/AbstractShellIntegrationTest.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/StreamCommandTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTests.java

- Limit stream name length to be `20` to allow the resolved app name length inside the allowed limit of 58 chars.

Fix stream name length in tests

---

.travis.yml
README.md

Based on the research [via: [3004#issuecomment-479540265](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3004#issuecomment-479540265)] and after discussing with @markpollack, we have decided to remove Codecov integration from SCDF. 
False alarms is one thing; more than that, we don't appear to be using this tool effectively for each of the PRs, so it'd be good to reduce the noise. We will switch to Sonar or something else to add a test-coverage badge in the README eventually.
Resolves #3004

Remove Codecov integration

---

spring-cloud-dataflow-server/docker-compose.yml

- Revert https://localhost:3000 to http://localhost:3000 as grafana's container currently is not configured to accept https requests.
Resolves #3111

Fix docker-compose's grafana url prefix

---

pom.xml
spring-cloud-dataflow-server/pom.xml

- Remove our explicit definitions to rely version(8.18) coming from
a parent build. This handled CVE warning with a used version.

Change com.puppycrawl.tools plugin version

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-shell-core/pom.xml

- Drop hsqldb from poms and docs as it's not supported anymore.
- Drop manual migration section from docs as things are handled by flyway.
- Polish db sections for local server and add notes about
MySQL 8+ and MariaDB 10.3+.
- Testing work has been done in db acceptance tests.
- Fixes #3255
- Fixes #3256

Polish database support

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration.adoc

- Now simply pointing to apache resolver as
we don't use aether anymore.
- Fixes #3258

Replace aether to apache in docs

---

pom.xml

- Cloud build is now using latest junit5 deps which caused
mismatch with surefire plugin. At least internally it got
NoSuchMethodError as surefire also depends on junit5.
- We use explicit surefire configuration and this commit
changes it to same version as cloud build which seems
to fix this junit5 issue and thus putting restdocs
back to business.
- Fixes #3421

Fix restdocs generation

---

spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java

- Remove stacktrace print which for some reason were left in
place during original boot 2.2.x upgrade work.
- Fixes #3428

Polish shell output

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests.java

- When the stream definition is updated after the successful update, the stream description needs to be updated as well.
- Add test to check
Resolves #3486

Preserve stream description upon update

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc

The docs specify `SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_DEPLOYMENT_TASK_MEMORY` but the correct env variable is `SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_DEPLOYMENT_MEMORY`

Remove "TASK_" prefix from deployment memory example

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

- Since Cloud Foundry manages task executions by the given task name, the
log retrieval needs to be limited only to the latest acceptable task execution only.
- Make sure to check the task execution is the latest when retrieving the logs in case of CF
- Update tests
Resolves #3515

Retrieve log for latest task execution on CF

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/BaseDocumentation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskDeleteService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerServiceTests.java

- The DefaultTaskDeleteService should import the scheduler service when the task and schedules are enabled.
- Conditionally import the `SchedulerService` bean
- Remove explicit `local` scheduler no-op which was used only for tests
- Update documentation and scheduler service tests
Resolves #3546

Conditionally import SchedulerService

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/diff/TaskAnalysisReport.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/diff/TaskAnalyzer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/diff/TaskManifestDifference.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/diff/TaskAnalyzerTests.java

- This commit adds support for processing task arguments
which are passed as `-foo=bar` and `foo=bar` format.
- Relates to an issue PR'd with #3555 which broke
tests as new tests for these pros were added after
PR were issued.
- Polish DefaultTaskExecutionService

Support task arguments with single and no dash

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc

The no-maven situation continues to come up at customers. Unfortunately, we don't yet list the SCDF App Tool in the docs, so this commit adds just that.
It'd be nice to backport it to 2.2.x.

Add SCDF App Tool to the docs

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java

vs just failing.   Also log the exception with a warning.
resolves #3523

If the log retrieval throws an exception give the user a message

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcDataflowTaskExecutionMetadataDao.java

- Remove extra semicolon from end of a query as it seems to cause
issues with some drivers(oracle and possibly db2). Also
polish that query to remove new lines.
- Fixes #3664

Fix manifest query

---

spring-cloud-dataflow-docs/src/main/asciidoc/applications.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

- Update `Applications` list
- Remove stale and deprecated apps from the list 
- Remove App older release-train coordinates from the docs (i.e., Dearborn / Darwin)
- Remove explicit GA-link references; the `lates` URL going forward is sufficient

Update OOTB application coordinates

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DockerComposeIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DockerComposeTestProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

- Add kubernetesAppHostSuffix property to configure the Ingress server host name as a suffix of the exposed App Host URLs
- Remove obsolete K8s App URL resolution code.
Resolves #3738

Port the K8s App Host URL resolution

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowITProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DockerComposeIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/TaskScheduleIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactoryProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/task/dsl/Task.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/task/dsl/TaskSchedule.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/task/dsl/TaskScheduleBuilder.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/task/dsl/TaskSchedules.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/task/dsl/Tasks.java

- Add Task Schedule DSL (under test utils)
- Port the Schedule ATs into TaskScheduleIT. Later is run only for K8s or CF ATs and ignored for Docker Compose installation.
- Pot the Stream Confg Server test (run only on CF).
- Rename DockerCompseIT to DataFlowIT.
- Improve the logging info.
Resolves #3737

 Port the AT schedule tests to the IT test suite

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/support/StepExecutionJacksonMixIn.java

- To overcome future errors in `JobCommandTests` exclude `jobExecution` if
client side `StepExecutionJacksonMixIn` is used as what happens with those
tests when hateoas 1.0.2 is brought in.
- Issue will happen with real server/shell but we can't do more clever
things until shell is fully upgraded to boot 2.x.
- Fixes #3755

Exclude jobExecution on client side

---

pom.xml
spring-cloud-dataflow-audit/src/main/java/org/springframework/cloud/dataflow/audit/service/AuditRecordService.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/security/support/CloudFoundrySecurityService.java
spring-cloud-dataflow-rest-client/pom.xml
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/StreamDefinitionResource.java
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeStreamsControllerV2.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/SqlCommand.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/TaskDeleteService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionInfoService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskAppDeploymentRequestCreator.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/StreamDeployer.java
spring-cloud-dataflow-server/pom.xml
spring-cloud-starter-dataflow-server/pom.xml

- Refactor parts of a build files to remove
errors and some warnings.
- For @NotNull warning we just import findbugs as
provided dependency as that's currently what
framework recommends.
- Polish javadocs so that we can at some point
start failing build for incomplete javadocs, etc.
- Fixes #3739

Clean build

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/RuntimeAppsDocumentation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsControllerTests.java

- When using `runtime apps --appId xxx` it effectively
on a server side iterates all apps to find a matching
deploymentId and then returns AppStatus for that. This
is painfully slow.
- To make this command even slightly usefull, replace backend
to use release information from a database and return
AppStatus from there for matching deploymentId.

Make runtime app instance faster

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc

The `{scdf-core-version}` token was removed from the docs module. There were a few lingering references to the unsupported tokens in the URLs, and this PR attempts to fix them.
Built it locally and tested it using:
> ./mvnw clean package -DskipTests -P full -pl spring-cloud-dataflow-docs -am
Resolves #3805
Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/3771

Fix broken links in the ref. guide

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java

- Instead of doing authorize request once, do it with
every request which will handle use of refresh token
if needed.
- Fixes #3882

Re-authorize jwt with every request

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
src/kubernetes/server/server-config.yaml
src/templates/kubernetes/server/server-config.yaml

- Set the Docker Hub token service uri within the `dataflow-server-defaults.yml`. E.g. 
```yaml
container:
registry-configurations:
default:
registry-host: registry-1.docker.io
authorization-type: dockeroauth2
extra:
"registryAuthUri": 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repository}:pull&offline_token=1&client_id=shell'
```
- Remove the redundant k8s yaml configs. 
Resolves #3904

Pre configure the DockerHub Auth URI

---

spring-cloud-dataflow-server/docker-compose-postgres.yml
spring-cloud-dataflow-server/docker-compose.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java

- update the docker-compose files to use skipper image entrypoint pointing to /maven/spring-cloud-skipper-server.jar instead of /spring-cloud-skipper-server.jar
- Update the SCDF (2.6.0.BS) and SKIPPER (2.5.0.BS) docker images versions used for IT

Update the new Skipper image entrypoint

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTasklet.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTaskletTests.java

In the 2.5.x we have resolved most of the issue. However I did identify that on restart that a duplicate parentExecutionId is introduced by CTR on K8's 
resolves #3656

Updated so that parentexecutionid isn't duplicated

---

spring-cloud-dataflow-server/docker-compose-prometheus.yml
src/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
src/templates/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml

- Update to prometheus proxy server version based on rsocket-RC7compatible.
- Ensures compatibility with the Spring Boot 2.3.0.RC1+ (also based on RC7).
- Compatible with the older apps based on the prometheus proxy 0.9.0 client.
- Fix the 0.11.0 version in the k8s deployment configuration.
Resolves #3929

Update the prometheus proxy server version

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server/pom.xml
spring-cloud-starter-dataflow-ui/pom.xml

- Add spring-cloud-starter-dataflow-ui to ease for those doing
custom builds.
- Essentially move UI from server core to module creating
main fatjar.
- Custom builds then need to add starter or define their own
UI dep without a need to start excluding deps.
- Fixes #3961

Move UI dep away from server core

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/AppRegistration.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/repository/AppRegistrationRepository.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/service/AppRegistryService.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/service/DefaultAppRegistryService.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/AppRegistrationResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java
spring-cloud-dataflow-server-core/src/test/resources/META-INF/test-apps-multi-versions.properties

- When the apps are retrieved, we need to have an ability to include all the versions associated with the app
- Add a request parameter `defaultVersion=true` to retrieve only the apps that have default version set to true and along with the versions for that app
- Update REST API documentation
- Add/update tests
Resolves #2039

Applications list to include all the versions

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc

This is related to https://github.com/spring-io/dataflow.spring.io/issues/259 .   Currently the description of all deployment properties are here. We should move them to the microsite at some point.

Added env to the CF deployment properties table

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

The docs had been updated but noticed an old link that can be removed.
resolves #4069

Removed old link to the composed task runner app starter

---

spring-cloud-dataflow-server/docker-compose-prometheus.yml

- Change the websocket port from 8081 to 8086
- explicitly configure the tcp and websocket ports:
- micrometer.prometheus-proxy.websocket-port=8086
- micrometer.prometheus-proxy.tcp-port=7001
Resolves #4082

Configure different prometheus-rsocket ports

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Using comma as separators is deprecated now.

Stream Applications with app type should be separated by single pipes

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobExecutionsDocumentation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobServiceTests.java

We were expecting  the platform name  to be in the job param but, since the value is non identifying, it is excluded from the job param.
resolves #4080

Restart failed job now uses task arg to get platform

---

spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolver.java
spring-cloud-dataflow-configuration-metadata/src/test/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolverTests.java
spring-cloud-dataflow-server/README.adoc
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java

- Delegates the unescaping to the RestTemplate interacting with the container registries.
- Add IT test.
Resolves #4084

Remove second unescaping of Container Metadata

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

Fix the inability to destroy all Tasks at once from Shell (using task all destroy) when Authentication is enabled.
Applied same logic as for Streams to Task definitions, executions and schedules.

Allow deletion of all tasks definitions/executions/schedules when Authentication is enabled

---

pom.xml
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/configuration/DataFlowTestConfiguration.java
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/MetricsReplicationEnvironmentPostProcessor.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/web/WebConfiguration.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server/docker-compose-influxdb.yml
spring-cloud-dataflow-server/docker-compose-prometheus.yml
spring-cloud-dataflow-server/docker-compose-wavefront.yml
spring-cloud-dataflow-server/src/main/java/org/springframework/cloud/dataflow/server/single/DataFlowServerApplication.java
src/grafana/influxdb/docker/grafana/Dockerfile
src/grafana/prometheus/docker/grafana/Dockerfile
src/grafana/prometheus/docker/grafana/dashboards/scdf-servers.json
src/grafana/prometheus/docker/prometheus-local/Dockerfile
src/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
src/templates/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml

- Back port Server dashboard configurations.
- change the wavefront activation metrics to the spring.clodu.dataflow.server.*
- add SCDF application metrics tag to be the name of the jar.
- enable SCDF HTTP metrics percentiles.
- Upgrade to latest Prometheus Rsocket RPoxy 1.2.1
- Fix broken configurations in prometheus and influx dockcker-compose files.
- Update prometheus and Grafana container image versions.
- retrofit the scdf-servers.json dashboard for Grafana.
- Change the 8081 prometheus-rsocket-proxy to 8086 to a avoid conflicts with the McAfee daemons.

Align with 2.7.x WF tile activation metrics

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/MetricsReplicationEnvironmentPostProcessor.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/MetricsReplicationEnvironmentPostProcessorTests.java

- Ignore the unresolvable placeholders in the MetricsReplicationEnvironmentPostProcessor. The check is reenabled after the processor is done.
- Add tests
Resolves #4193

Handle unresolved placeholders for metrics copy

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java

This PR fixes #4190
- Added validation when the task is launched depending on the platform launched in.
- Returns a meaningful message if the task was > 63 characters.

Added validation for task name length depending on launch platform

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobServiceTests.java

resolved #4204
The original intent was to use the entire key that was returned from batch.
However when relaunching a job from CF it will fail.  That is because the build pack requires a triple escape to use `(` character ie.`\\\(`
This also causes a problem when passing this value as a property when using shell entrypoint for k8s.
So since this is just a hint to batch, we will remove this info and let batch figure out the correct type.

Removed the type hint from the job params on job restarts.

---

spring-cloud-dataflow-server/docker-compose.yml

- Upgrade docker compose Kafka and Zookeeper to 5.4.3.
- Set the Kafka metrics.recording.level to DEBUG to enable detailed Kafka Stream & Task Metrics collection:
https://docs.confluent.io/current/streams/monitoring.html#configuring-metrics-granularity
Part of #4209

Upgrade docker compose Kafka to 5.4.3

---

src/kubernetes/grafana/grafana-deployment.yaml
src/kubernetes/server/server-config.yaml
src/kubernetes/server/server-deployment.yaml
src/kubernetes/skipper/skipper-deployment.yaml
src/templates/kubernetes/server/server-config.yaml

- Use a single (Data Flow server) metrics configuration and let the MetricsReplicationEnvironmentPostProcessor replicate the metrics to the Stream and App configurations.
Part of #4103

Back-port the Metrics replication config for k8s

---

spring-cloud-dataflow-server/docker-compose-prometheus.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

- Replace the reference to test SNAPSHOT app image. Looks like bamboo caches or fails to retrieve latest images.
- reduce the Dataflow logging churn.

Improve the ITs stability on Bamboo env

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/application-stream-common-properties-defaults.yml

- inject wf.application.name and wf.service properties to the deployed streaming apps to enable the WF tracing support.
Resolves #4333

Inject WF tracing properties to the stream apps

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

We were currently saving the qualifed deployer properties in the manifest.
This format could not be used on relaunch.  This change stores the deployer properties as the user entered them, so they can be used for relaunches.
resolves #4306

Task Manifest stores deployer props as written by user

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/TaskExecutionInfoService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionInfoService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

- If version is not explicitely passed in with launch,
don't switch back to default version.
- This fixes default case with shell when you just relaunch,
but doesn't change anything on a UI side where version is
still the one defined in a form(not yet rehydrated from
previous manifest).
- Fixes #4381

Restore task app version from manifest

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtils.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

- With original impl for #4258 and #4265, we changed ctr subtask
to get created with labels if those were in a dsl but forget
to do same change when passing version info around.
- Now properly using label with version.

Use correct version options with composed tasks

---

spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

- use the maven-jar-plugin to generate standalone jar for the ITs.
- Harden the ITs getApplicationUri utilities to ensure it works with k8s platforms.
- Fix an issue with the logfile path to ensure proper working with K8s platforms.
Resolves #4400
Part of the https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/332 Epic.

Generate standalone ITs tests jar

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskSaveService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

$END will not be validated as a app

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/AbstractBaselineCallback.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/postgresql/PostgresBeforeBaseline.java

- Previously with postgres driver there was an
attempt not to use transactions as those always
abort it even with query errors. This as a naive
way would cause migration issues if something
else goes wrong and database may be left in
a wrong state.
- With postgres, move back to transactions and
do a table exists check which should be more
reliable which then seem to survive in tests
where we manually break database and next
launch attempt after "fixing" database looks
to bring things in a good condition.
- These new tests are not part of this commit
but coming in with a new integation tests
what I've run locally.
- Fixes #4370

Remove flyway transaction disable with postgres

---

spring-cloud-dataflow-server/README.adoc
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowITProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/IntegrationTestProperties.java

- Prepare to be able to add more sub-keys
under `test` and simply nest `test.docker.compose`.
- Fixes #4418

Nest options in DataFlowITProperties

---

spring-cloud-dataflow-server/README.adoc
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowOperationsITConfiguration.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/IntegrationTestProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java
spring-cloud-dataflow-server/src/test/resources/application.properties

- Replace the proprietary dataflowTemplate builder by s-c-d-f-rest-client#DataFlowClientAutoConfiguration
- Remove the custom test.platform.connection.dataflowServerUrl property in favor or spring.cloud.dataflow.client.server-uri .
- Use spring.cloud.dataflow.client.skipSslValidation to disable SSL validation.
- Create a DataFlowOperationsITConfiguration configuration to be used by ITs/ATs for configuring the DataFlowTemplate and the RuntimeApplicationHelper instances.
- Streamline the ITs/ATs implementation to ensure that all interactions with the SCDF server (including http-post and app/actuators) are funneled through the single dataflowTemplate + restTemplate.
Resolves #4433

Use s-c-d-f-rest-client for all IT/AT connections

---

spring-cloud-dataflow-server/pom.xml

- This will bring back driver to a fat-jar.
- Fixes #4454

Remove postgres from test dependency

---

spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerRegistryProperties.java
spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/authorization/DockerConfigJsonSecretToRegistryConfigurationConverter.java

When approriating the .dockerconfigjson secrets for Container Metadata retrieval
replace the default `https://index.docker.io/v1/` or `domain.io` docker-server values
to `registry-1.docker.io`.
Resolves #4428

Replace k8s secret's default server values

---

spring-cloud-dataflow-server/README.adoc
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowOperationsITConfiguration.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/IntegrationTestProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactoryProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

Allows the integration tests configuration to install HTTPS based SCDF, Skipper and OOTB apps (using docker-compose) and run the ITs agains it.
- Add additional ITs properties to configure the HTTPS docker-compose installation programmatically. 
- Add workaround to skip ssl-validation for the palantir docker-compose/fork in case of https services.
- Add README samples.

Support HTTPS docker-compose ITs

---

pom.xml
spring-cloud-dataflow-platform-cloudfoundry/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server/pom.xml

- Remove dep handling of fabric8
- Move config-client starters from core packages into
server module. This fixes testing issues and let
those runtime deps to be in fatjars.
- Fixes #4506
- Fixes #4507

Fix changes in cloud 2020.0.2

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskProperties.java

- Makes composedTaskAppArguments and composedTaskAppProperties as
groups as values of those are maps.
- Fixes #4529

Define non simple ctr props as nested

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/DefaultStreamDefinitionService.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/StreamDefinitionServiceUtilsTests.java

- when the app property has the value containing '|' make sure to add quote
- update test
Resolves #4161

Fix stream dsl reconstruction

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Now SCDF will not throw a NPE
resolves #4575

Handle cases where an invalid platform is specified.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskDeleteService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

If there is no task deployment when a task definition is deleted SCDF will delete all app resources for the task definition name across all platforms.
If there is a task deployment for that task definition, then it will only delete those app resources associated with that task deployment.
This is to resolve the case where a task launch failed on the platform and thus no task deployment record is created.  Hence we don't know what platform the launch attempt occured.
resolves #4574

Complete task task resource cleanup on task deletion.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobServiceTests.java

resolves #4484
This PR resolves the NPE that was reported and allows dataflow to
restart apps if there is only one platform.  If there is more than
one platform, there is no metadata to know which one is the correct platform.
The solution is to start storing metadata on schedule launches.

Fixes NPE issue when restarting externally launched jobs

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

resolves #4622
Instead of using platform to determine which resource type to use for the test it looks at the timestamp's resource type that was registered at the beginning of the integration test.

Updated multipleTaskAppVersionTest to use IT timestamp  resource

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

This covers scenarios where a task was launched by another task (i.e. remote partitioned jobs)
However, this will work only on K8's and CF.
Based on how dataflow launches tasks using the local deployer this will not work for child apps launched from a task running using the local deployer.
resolves #3857

Uses parent task's platform to stop task if it has no platform.

---

spring-cloud-dataflow-autoconfigure/src/test/java/org/springframework/cloud/dataflow/autoconfigure/local/AbstractSchedulerPerPlatformTest.java
spring-cloud-dataflow-autoconfigure/src/test/java/org/springframework/cloud/dataflow/autoconfigure/local/SchedulerPerPlatformTest.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryPlatformProperties.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundrySchedulerClientProvider.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformAutoConfiguration.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformFactory.java
spring-cloud-dataflow-platform-cloudfoundry/src/test/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformFactoryTests.java
spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformFactory.java
spring-cloud-dataflow-platform-kubernetes/src/test/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformFactoryTests.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/SimpleTestScheduler.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskSchedulerControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerServiceMultiplatformTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerServiceTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/CloudFoundrySchedulerTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/MultiplePlatformTypeTests.java

resolves #4262
Updated to support deployer props instead of scheduler props.
The following issues need to be reviewed and merged first:
https://github.com/spring-cloud/spring-cloud-deployer/pull/349
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/457
https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/378
These need to be built prior to building dataflow.
Also note that for CF deployments there has been a change in the properties
`    SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_SCHEDULER_SCHEDULERURL: https://scheduler.sys.somewhere.com`
`SPRING_CLOUD_DATAFLOW_TASK_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_DEPLOYMENT_SCHEDULERURL: https://scheduler.sys.somewhere.com`

Deprecates the use of scheduler properties

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/FeaturesProperties.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskSaveService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceUpdateTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

- This is to add backwards compatibility support only on local and CF environments
- Users need to specify `spring.cloud.dataflow.features.underscore-names-enabled" feature flag
to enable underscore in the stream/task names
- Add tests
Resolves #4640
Resolves #4642

[2.7.x] Allow underscore in stream/task names on non-K8s environment

---

spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerImageRestTemplateFactory.java
spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/authorization/DropAuthorizationHeaderRequestRedirectStrategy.java
spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java
spring-cloud-dataflow-server/src/test/resources/docker-compose-container-registry-it.yml
src/docker-compose/docker-compose-debug-dataflow.yml
src/docker-compose/docker-compose-debug-skipper.yml

- Drop Authorization headers only for Basic auth.
- Add support for GitHub Container registry.
- Jackson MessageConverter support for text/plain. The Github CR response's media-type is always text/plain although the content is in JSON
- Normalize Azure redirect URI
- Add Container Registries IT tests
- Add SCDF image build configuration
- Fix docker compose debug conf for build pack images
Resolves #4412

Add drop auth headers redirect strategy for Azure

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskSaveService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

- Instead of restricting the stream creation for all the platforms, restrict the invalid stream/task name only after when they are about to be deployed/launched.
Since SCDF is aware of the underlying platform only at the time of deployment, we go with this approach of validation
- Also, to provide compatibility with the previous deployments on local and CF, we don't enforce this validation on non K8s environments
Resolves #4640

Validate K8s specific stream deployment/task launch

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java
spring-cloud-dataflow-server/src/test/resources/docker-compose-it.yml
src/docker-compose/docker-compose-dood.yml
src/templates/docker-compose/docker-compose-dood.yml

- For DooD mode configure the Task port range 20200-61000 to be outside the default APPS_PORT_RANGE.
- Fix a missing DockerComposeFactoryProperties.TEST_DOCKER_COMPOSE_APPS_PORT_RANGE support to allow the DockerComposeFactory
control the (in Skipper running) apps port range when running DataFlowIT.
Resolves #4712

Fix ITs task ports conflict

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtilsTests.java
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java

Since the blank is the delimiter for arguments they will be trimmed.
Also since this created empty argument entries that for oracle caused a NPE, data flow will treat all null args as empty strings.  (this is for existing records)
Resolves  #4748

Updated to handle trailing blanks in arguments

---

src/kubernetes/server/server-config.yaml
src/templates/kubernetes/server/server-config.yaml

Mysql is still the default db for mariadb

Set the db for mariadb to mysql

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Documents changes made for gh-412
> ℹ️ Marked as "Draft" since there is a logical dependency on https://github.com/spring-cloud/spring-cloud-deployerkubernetes/pull/472

Draft: Add docs for Kubernetes seccompProfile on PodSecurityContext.

---

spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/H2ServerConfigurationTests.java
spring-cloud-dataflow-server/pom.xml

This adds the h2 dependency back into the server core module. 
Removing it broke the local mode that is outlined in the Getting Started guides. We attempted to upgrade to h2 `2.1.210` but it does not play well w/ the rest of the ecosystem yet. 
The tradeoff is that SCDF 2.x will continue to get CVE alerts when scanned. 
We may attempt to exclude it before we GA though.

Add h2 dependency back in

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AuditRecordControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceUpdateTests.java
spring-cloud-dataflow-server-core/src/test/resources/META-INF/test-apps-overwrite.properties
spring-cloud-dataflow-server-core/src/test/resources/META-INF/test-apps.properties
spring-cloud-dataflow-shell-core/src/test/resources/META-INF/test-stream-apps.properties
spring-cloud-dataflow-shell-core/src/test/resources/META-INF/test-task-apps.properties
spring-cloud-dataflow-shell-core/src/test/resources/commands/registerSink_log.txt
spring-cloud-dataflow-shell-core/src/test/resources/commands/registerTask_timestamp.txt

The SCDF server core tests are broken as they rely on the `1.0.0.BUILD-SNAPSHOT` version of the stream apps which no longer exist in Artifactory.
Moves to the latest `3.2.0` artifacts and adjusts tests accordingly.

Update tests to use 3.2.0 version of artifacts 

---

pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataflowOAuthSecurityConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/SpringDocAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/support/SpringDocJsonDecodeFilter.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server-core/src/main/resources/META-INF/spring.factories
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/EmptyDefaultTestApplication.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/SpringDocAutoConfigurationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/SpringDocIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/SpringDocJsonDecodeFilterTest.java
spring-cloud-dataflow-server-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This is a continuation of @klopfdreh original PR [here](https://github.com/spring-cloud/spring-cloud-dataflow/pull/4836). 
@klopfdreh I squased/rebased your PR on 2.9.x and then cherry-picked to a userbranch off of main. I will close your original PR that is in 2.9.x and we can continue to work from here. 
I think we are good on testing now. 
**Here is what is remaining:**
@klopfdreh if you can do the above that would be great. Otherwise I will get around to it next weekend. 
**Steps to see enable**
1. Start SCDF server with Springdoc enabled properties
```shell
-Dspringdoc.api-docs.enabled=true -Dspringdoc.swagger-ui.enabled=true
```
OR
```yaml
springdoc:
api-docs:
enabled: true
swagger-ui:
enabled: true
```
2. Navigate to http://localhost:9393/v3/api-docs (you will see the openapi …

Springdoc integration

---

spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-server-core/pom.xml

Fixes #4866  - Dependencies added SCDF server core and CTR. Depends on https://github.com/spring-cloud/spring-cloud-dataflow-build/pull/72

Add oracle jdbc driver dependencies

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/IntegrationTestProperties.java

tasklauncher test fails on CF now that I fixed the tasklauncher-sink app registration issue

Make dataflow server uri a test property

---

spring-cloud-dataflow-server/pom.xml

ℹ️ I did not put this into a separate Maven profile. If we use a profile, the user will still need to build the application on their own as this is a build time option. 
The executable version of the jar works with both 
* `java -jar spring-cloud-dataflow-server-2.9.5-SNAPSHOT.jar`
* `./spring-cloud-dataflow-server-2.9.5-SNAPSHOT.jar`
I do not see a reason to not just make it executable by default. Also, none of the caveats listed in the [Boot docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment.installing) apply in our case.
If you run `less` on the generated jar you can see it is just a bash script in front of the binary jar contents. 
Fixes #4941

Make spring-cloud-dataflow-server jar executable

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/container/DataflowCluster.java

- Similar to the fix implemented in Testcontainers (
https://github.com/StefanHufschmidt/testcontainers-java/commit/45c207f045ae6aeff943e49dbacad302c1c84cdd) set `encypt=false`
Fixes #4978

Disable encryption for Mssql test container

---

src/carvel/templates/bundle/repo/versions.yml

kapp timeout of 5min is too short when deploying into mutiple namespaces at the same time.

Increase deploy timeout

---

src/carvel/config/dataflow-deployment.yml
src/carvel/config/skipper-deployment.yml

Adding a startup probe can reduce the time it takes for application to register live/healthy. 
The initial time of live and healthy only start when startup probe reports success.

Added startup probe

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-database.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc

This handles the Dataflow ref guide updates - Skipper to follow.
I have created a common database adoc and included in both places that were previously talking about the details of which database/driver is supported etc.. 
This will not be the final suggested mechanism for users to extend the classpath as @corneil has another way that is less intrusive and will be addressed by [spring-cloud-dataflow#5083](https://github.com/spring-cloud/spring-cloud-dataflow/issues/5083).
I have attached generated PDF for your viewing pleasure while reviewing in case you do not have the IDEA asciidoc plugin etc.. These will NOT be checked in. 
- [configuration-kubernetes.pdf](https://github.com/spring-cloud/spring-cloud-dataflow/files/9528541/configuration-kubernetes.pdf)
- …

Update database section of ref guide

---

spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/job/StepExecutionHistory.java

These attributes are not actively being used and cause confusion.
* The reason that the StepExecutionHistory was not deprecated as a whole is that duration and count are used in the percent complete feature for steps offered by the UI.
* Also added some documentation to the StepExecutionHistory class.
* Notifying folks of a deprecation via the RESTFul API has to be done through documentation for now.
* jThere was an option do so via the schema of the JSON however, based on my reading the plugin in Jackson that allows us to add a schema will soon no longer be supported.

Deprecates attributes of the StepExecutionHistory

---

spring-cloud-dataflow-autoconfigure/src/test/java/org/springframework/cloud/dataflow/autoconfigure/local/SchedulerPerPlatformTest.java
spring-cloud-dataflow-platform-kubernetes/src/test/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesPlatformPropertiesTests.java
spring-cloud-dataflow-platform-kubernetes/src/test/resources/application-kubernetes-platform-properties.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/CloudFoundrySchedulerTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/KubernetesSchedulerTests.java

- Add 'spring.cloud.kubernetes.client.namespace' prop which is required in SCK 2021.0.5

Fix failure in Kubernetes tests

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/application-stream-common-properties-defaults.yml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests-install.yml

Adds actuator endpoint props in the common stream resource props which gives them to all deployed stream apps. 
- Verified manually in local stack. 
- Integration test added as well
Fixes #4753

Add actuator props to stream on deployment

---

src/docker-compose/docker-compose-mysql.yml

The guide for running dataflow locally does not work when choosing mysql as the database provider.  Full details in issue #5167

Fix for mysql when using docker compose to run local

---

src/docker-compose/docker-compose-prometheus.yml

This allows apps that terminate regardless of the reason to record their entire suite of metrics data.  This is important for especially for ephemeral apps.

Updates the prometheus proxy version in docker-compose yml

---

.github/actions/build-package-bundle/action.yml

Fixes #5261
Update `.github/actions/build-package-bundle/action.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/ -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=bundle-path::$PACKAGE_BUNDLE_GENERATED"
```
**TO-BE**
```yml
echo "bundle-path=$PACKAGE_BUNDLE_GENERATED" >> $GITHUB_OUTPUT
```

Replace deprecated command with environment file

---

spring-cloud-starter-dataflow-server/src/main/resources/dataflow-server.yml

- Add `mavenCentral` remote rep
- Edit `springRepo` (`libs-snapshot` -> `/snapshot`)
See #5321
**Prove its broken**
- Switch to `/snapshot`
- Clear my local m2 cache for `org/springframework/cloud/stream/app`
- Run SCDF + Skipper locally
- Register bulk kafka/maven apps from SCDF UI
- Create `time | log` stream def
- Deploy `time | log` stream def
- 💥 
**Fix**
- Add mavenCentral remote repo
- Redo the above steps and see that the 💥 goes away

Adjust `maven.remoteRepositories` for Artifactory cutover

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/MetricsReplicationEnvironmentPostProcessor.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/MetricsReplicationEnvironmentPostProcessorTests.java

- Enhance the existing replication of the server metrics props ('management.metrics.export.*') by also replicating a Spring Boot 3 variant so that Spring Boot 3 stream|task apps will also have the proper props available.

Replicate metrics props for Boot 3 variants

---

spring-cloud-dataflow-classic-docs/pom.xml
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDeploymentsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskLogsDocumentation.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

* Updated TaskExecutionService tests to replaced deprecated code.
* Updated TaskLogsDocumentation to use Awaitility instead of a thread.sleep.
* Updated StreamDeploymentDocumentation to remove unnecessary prints that cluttered the log.
* Updated StreamDeploymentDocumentation to remove unnecessary thread.sleeps.

Test and Doc test cleanup

---

spring-cloud-dataflow-composed-task-runner/src/main/resources/META-INF/dataflow-configuration-metadata.properties
spring-cloud-dataflow-composed-task-runner/src/main/resources/META-INF/spring-configuration-metadata-whitelist.properties
spring-cloud-dataflow-composed-task-runner/src/main/resources/META-INF/spring-configuration-metadata.json
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskCtrControllerTests.java

Tested it locally but found an issue in UI deleting property when navigating between builder and freetext
where the task properties were not reconstituted on the UI.   
Resolves #5229

Add support to retrieve metadata on task properties

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc

Updates the section of the Dataflow reference docs that discusses the addition of database drivers and then building the dataflow project with a link to the section on  how to extend the classpath to include the drivers.
resolves #5380

DB Driver section of reference document updated

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java

The DefaultTaskJobTests (integration) will now pass.

TaskJobExecution was using jobExecutionId for the taskExecutionID

---

spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtilsTests.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java

Execute the following steps in SCDF Shel to reproduce the issue.
```
app register --bootVersion 3 --name timestamp3 --uri maven://io.spring:timestamp-task:3.0.0 --type task 
task create --name ts3 --definition timestamp3
task list
```
**Bug** 
This steps above caused the shell to crash with no exception. 
**Cause**
An additional header of `schemaType` was added to task definitions.  
**Additional fix**
* Also fixed tests in the DeployerPropertiesUtilTests.

Task list shell command will now work properly.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java

There is a clear on the deploymentProperties that removes scheduling information as well as the properties for the composed task runner. Removing it allows those properties to be used and schedule to be created.
I did not see a side-effect but may have missed something.

Scheduler does not create schedule for CTR apps

---

spring-cloud-dataflow-docs/src/main/asciidoc/spring-boot-3x.adoc

Added docs on CTR not requiring any special instructions for launching. A note was added to remind users to select the appropriate boot version during app registration

Spring Boot 3.x support doc needs section on CTR

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java

Updated spelling mistake from prosess to process
fix #5455

fix: Spelling mistake for process

---

spring-cloud-dataflow-parent/pom.xml
spring-cloud-skipper/pom.xml

The commons-compress has a CVE in version `1.22` which is fixed in version `1.24.0`. For some reason, testcontainers.jar brings in commons-compress at `api` configuration which in turn puts it on the classpath even though testcontainers is a 'test' configuration.

Update the version of commons-compress brought in by testcontainers

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-server-core/pom.xml

The git-commit-id plugin was relocated from
`pl.project13.maven:git-commit-id-plugin:4.9.9` to `io.github.git-commit-id:git-commit-id-maven-plugin:4.9.9`.

Update location of the git-commit-id plugin

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AboutDocumentation.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

This switches to the `simple` mode of the git info contributor. Otherwise we would have to document every single field in the gigantic response returned from the `full` mode.
See #5507
⚠️ @felipeg48 you will need to update the code in the [UI PR counterpart](https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1971) as the new path will be `gitAndBuildInfo.git.commit.id`.

Document the gitAndBuildInfo field returned from the AboutController 

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/oracle/V9__Boot3_Batch5_Job_Execution_Params_Column_Fix.java

This commit introduces an Oracle schema migration that updates the BOOT3_BATCH_JOB_EXECUTION_PARAMS table to use the newer Batch5 parameter columns.
I reproduced the bug locally against (with the help of the newly added https://github.com/spring-cloud/spring-cloud-dataflow/wiki/Oracle-on-Mac-ARM64) and then fixed the issue and watched the bug go bye-bye.
Resolves #5534
ℹ️ I created #5545 to add test coverage for this use case.

Fix columns in BOOT3_BATCH_JOB_EXECUTION_PARAMS

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTasklet.java
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/support/UnexpectedTaskExecutionException.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTaskletTests.java

It would be great if the CTR throws an `UnexpectedTaskExecutionException` in favor of `UnexpectedJobExecutionException` so that it is possible to create an `ApplicationListener` which can handle certain error causes.
Because the `TaskExecution` itself is not serializable, the fields are assigned to the `UnexpectedTaskExecutionException`.
If this code is fine for you it also needs to be merged into: https://github.com/spring-cloud/spring-cloud-dataflow/pull/5368
The `UnexpectedTaskExecutionException` also uses the `ExitCodeGenerator` interface so that the error code of a task which has failed is also forwarded through the CTR to its caller.
If the exit code is `null`, the `UnexpectedTaskExecutionException` returns `-1`

feature: UnexpectedTaskExecutionException

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/AggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java

Fix find by name query ordering.
Fix find by name not found query.
Improve test case readability.
#5484

Ensure sub-query use for Job instances.

---

spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml

- Remove spring-cloud-starter-common-security-config-web as a test-jar dependency as its know to cause issues with jdt based ide's.
- skipper/dataflow servers don't even need it and composed task runner can use spring-cloud-common-security-config-web as plain test scope.
- This should make project structure import into vscode work again.

Remove use of security starter

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AuditRecordControllerTests.java

AuditRecordControllerTests ocassionally fails on the testRetrieveAuditRecordsFromGivenDateToNull test.
This is because it is expecting 2 audits but ocassionally gets 3 because a create audit for the last entry isn't recorded till after the endTime is recorded.
This commit adds a 30 second max wait for all create audits to complete.

Await for all audits to be recorded

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/database/support/DatabaseType.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/SimpleJobServiceFactoryBean.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/AggregateDataFlowTaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/AggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/JobServiceContainer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/AbstractJdbcAggregateJobQueryDaoTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/AbstractSimpleJobServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDaoRowNumberOptimizationTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/AbstractSmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/JobExecutionTestUtils.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/MySQL57SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/SqlServer2017SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/SqlServer2019SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/SqlServer2022SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/support/DatabaseTypeTests.java
spring-cloud-dataflow-server/src/test/resources/logback-test.xml
spring-cloud-dataflow-test/pom.xml
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/DB2_11_5_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/MariaDB_10_6_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/MariaDB_11_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/MySQL_5_7_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/MySQL_8_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/Oracle_XE_18_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/Postgres_14_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/SqlServer_2017_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/SqlServer_2019_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/SqlServer_2022_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/oracle/OracleContainerSupport.java

Use ROW_NUMBER in JdbcAggregateJobQueryDao to improve performance

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java

This alone was creating 10K lines of logs.

Limit excessive logging in DefaultSchedulerService

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobServiceTests.java

Following updates made:
1. Now supports Long type for boot3 app job parameters
2. Supports default format for boot 3 job parameters 
3. Added tests for both Boot2 and boot 3 job parameters.

Use boot3 notation when restarting a batch job

---

spring-cloud-dataflow-aggregate-task/src/test/resources/logback-test.xml
spring-cloud-dataflow-server-core/src/test/resources/logback-test.xml
spring-cloud-dataflow-server/src/test/resources/logback-test.xml
spring-cloud-skipper/spring-cloud-skipper-server/src/test/resources/logback-test.xml
spring-cloud-starter-dataflow-server/src/test/resources/logback-test.xml

This commit adjusts the log level during tests for Flyway packages to INFO as the current setting of DEBUG is drowning all other log statements.

Reduce Flyway logging to DEBUG during tests

---

README.md
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/support/SqlPagingQueryProviderFactoryBean.java
spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/AbstractSmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/JobExecutionTestUtils.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/DB2_11_5_ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/arm64/Db2Arm64ContainerSupport.java

This commit adds a custom Oracle/MSSQl/DB2 paging provider that is used only by the aggregate DAO. This is required because the standard paging provider that ships with Spring Batch 4.x does not properly handle sort key aliases when using nested ROW_NUMBER clauses for these databases.
Resolves #5531

Use custom paging provider for aggregate DAO queries

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/SimpleJobServicePostgresTests.java

We maybe caching too many contexts and thus we run out of db connections. 
This PR sets the max context cache size to 4.  The default is 32.
Thoughts?

Set context max size to flush db connections

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-local-k8s-development.adoc
src/deploy/k8s/set-ver.sh
src/deploy/k8s/use-mk-docker.sh

If the user hit the exit 0 (when using source) and they did not use bash  terminal would exit.
The user would not know why the terminal exited.
Updated script to just check to see if there is bash available.

Script should not end terminal if not using bash

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

Had to add entries to dependencyManagement sections because adding the version property wasn't changing all the versions. Presuming that some external dependencies includes 2.7.0 directly and not via a property and is encountered before boot dependencies.
Fixes #5643

Update json-path to 2.9.0

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DefaultEnvironmentPostProcessor.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

This gets past the server startup error @jvalkeal .
2 things...
**ONE** as you mentioned, we have to adjust ordering - but the important piece is that we run before the ConfigDataEPP (otherwise it will never see our dataflow-server-defaults).
**TWO** we opt-out of the new config server model via `spring.config.use-legacy-processing` for now. 
Now when you `java -jar target/spring-cloud-dataflow-server-3.0.0-SNAPSHOT.jar` it starts up. Onto the next failure - complaining about Flyway - BUT I did not have DB running so....

Fix startup and EPP ordering

---

spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/SpringDocAutoConfiguration.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/SpringDocAutoConfigurationTests.java

This commit updates to Open API 2.x which is the version that supports Boot 3.
The SpringDocs migration guide was followed:
https://springdoc.org/#migrating-from-springdoc-v1

Update SpringDoc OpenAPI to latest 2.x

---

spring-cloud-dataflow-autoconfigure/pom.xml
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/ApplicationConfigurationMetadataResolverAutoConfiguration.java
spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerRegistryAutoConfiguration.java
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-server/src/main/java/org/springframework/cloud/dataflow/server/single/DataFlowServerApplication.java
spring-cloud-dataflow-server/src/main/resources/application.yml
spring-cloud-skipper/spring-cloud-skipper-autoconfigure/pom.xml

* We had an issue where some of the auto configurations were not firing.
This is because when a user specifies the resource tag in maven,
the boot plugin expects the user to fill the resources manually vs. Its default behavior
* Also removed the version from the H2 dependency so that it can be managed by the bom
* Removed unnecessary `@Configuration` annotations where a `@Autoconfiguration` annotation is present
- Currently SCDF fails to start with errors around metrics.
- These will need to be re-added when metric migration begins
- Remove debug settings from previous commit

Add Autoconfiguration.imports to resource includes in pom.xmls

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/JdbcAggregateJobQueryMariadbDaoTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/JdbcAggregateJobQueryPostgresDaoTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/SimpleJobServiceMariadbTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionThinControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobStepExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerCleanupAsyncTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TasksInfoControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/TaskExecutionExplorerTests.java

The following tests contain a significant number of failing tests because of the Boot2 and Boot3 schema changes.
They have been disabled and tagged as `TODO: Boot3x followup` so that they can be re-enabled
in the future once we update the code to handle the schema changes

Disable all tests that are failling because of schema changes.

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AuditRecordControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionThinControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskSchedulerControllerTests.java

These slash marks are not required by Boot3 and cause the tests to fail.
* Simplify TestDependencies class so that it implements WebMvcConfigurer 
instead of extending WebMvcConfigurationSupport while creating the WebMvcConfigurer bean.   
* This PR will reduce the number of test failures and expose other test failures.

Remove the tailing / mark in the mockMVC urls

---

spring-cloud-dataflow-audit/src/main/java/org/springframework/cloud/dataflow/audit/repository/jpa/AuditRecordRepositoryImpl.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/repository/AppRegistrationRepositoryImpl.java
spring-cloud-skipper/spring-cloud-skipper/pom.xml

When migrating to the latest Hibernate we saw the following exception:
```
Caused by: java.lang.IllegalArgumentException: Already registered a copy: SqmBasicValuedSimplePath
```
This is because we were recreating a CriteriaQuery for our count Queries. Hibernate no longer allows us to do that,
but rather allows us to use the existing CriteriaQuery,
but use the convenience method createCountQuery to provide the criteria query for our createQuery.
Also removed 6.1.7 version for hibernate core  that allows us to use the Boot bom. 
This also caused some downstream issues where dataflow was using the old version brought in from skipper

Reuse CriteriaQuery when retrieving result count.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DefaultEnvironmentPostProcessor.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/DefaultEnvironmentPostProcessorTests.java
spring-cloud-dataflow-server-core/src/test/resources/dataflow-server.yml
spring-cloud-dataflow-server-core/src/test/resources/test.yml

This commit adjusts the change of the order attribute made in commit de5824797fe7d765d4cdeb4f5a8b1aebed2ed9d4. The default EPP in fact needs to run after the ConfigDataEnvironmentPostProcessor and before the ConfigDataMissingEnvironmentPostProcessor.

Adjust order of DefaultEnvironmentPostProcessor

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-shell-core/pom.xml
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/ShellCommandRunner.java
spring-cloud-dataflow-shell/src/main/resources/application.yml
spring-cloud-skipper/spring-cloud-skipper-shell-commands/pom.xml
spring-cloud-skipper/spring-cloud-skipper-shell/src/main/resources/application.yml

- Exclude spring-cloud-dataflow-common-persistence as it caused jdbc stuff in shell and then failures with datasource autoconfig
- Temporarily in tests use reflection as some methods in spring-shell are not public anymore. Long term todo is to migrate to new spring-shell testing utils
- Add commented shell log file settings which is a way to log hard shell startup errors

Upgrade spring-shell 3.2.2

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/SimpleJobServiceMariadbTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/SimpleJobServicePostgresTests.java

Improved Failing `SimpleJobServiceMariadbTests` and `SimpleJobServicePostgresTests` that was running out of connections. Dirties Context was remove connection pool without closing connections.

improve simple job service tests

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-server/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml
spring-cloud-starter-dataflow-server/pom.xml

added `<argLine>--add-opens java.base/java.util=ALL-UNNAMED</argLine>` to surefire-plugin and failsafe-plugin configurations.

fix jdbc driver failures smoketests

---

spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/StreamCommands.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/StreamCommandTemplate.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/StreamCommandTests.java
spring-cloud-dataflow-shell-core/src/test/resources/myproperties.properties

Currently a user can not set --propertiesFile option on a stream update command This fix allows users to use --properties or --properties file with a stream update command.
Added tests to verify
resolves #5783

stream update should not require --properties

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

* Updates Netty to 4.1.109.Final
* Updates Reactor BOM to 2020.0.43
* Updates Rsocket BOM to 1.1.4
The updates to Reactor and Rsocket are not absolutely necessary as they will use the updated Netty version. However, it is good hygiene to keep them up-to-date.
See #5780
Before this change:
```
cbono@cbono-a01 spring-cloud-dataflow % ./mvnw dependency:tree -Dincludes='io.netty' | grep -E '4.1.101' | wc -l
408
```
After this change:
```
cbono@cbono-a01 spring-cloud-dataflow % ./mvnw dependency:tree -Dincludes='io.netty' | grep -E '4.1.109' | wc -l
409
```
```
cbono@cbono-a01 spring-cloud-dataflow % ./mvnw dependency:tree -Dincludes='io.netty' | grep -E '4.1.101' | wc -l
0
```

Update Netty (and family) CVE-2024-29025

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-single-step-batch-job/pom.xml

The updated version (2.9.13) has 1 CVE for its use of json-path 2.6.0. 
This is mitigated by the pre-existing override to json-path 2.9.0.
Resolves #5794

Update Spring Kafka to 2.9.13 for CVE-2023-34040

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/ci.yml
.github/workflows/milestone-worker.yml
.github/workflows/release-worker.yml
.github/workflows/skipper-docs-name.sh

Updated CI workflows to set property with spring-cloud-skipper-* on skipper docs to ensure it is published to docs.spring.io
Fixes #5778

Updated CI workflows to publish skipper docs

---

spring-cloud-dataflow-parent/pom.xml

Update the dep. mgmt. entries for Tomcat embedded as the previous commit used the wrong groupId (missing `.embed` suffix).
See #5780

Fix Tomcat embedded dep. mgmt.

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

Resolves #5780
```
cbono@cbono-a01 spring-cloud-dataflow % ./mvnw dependency:tree -Dincludes='org.bouncycastle' | grep -E '1.73' | wc -l
45
```
```
cbono@cbono-a01 spring-cloud-dataflow % ./mvnw dependency:tree -Dincludes='org.bouncycastle' | grep -E '1.73' | wc -l
0
cbono@cbono-a01 spring-cloud-dataflow % ./mvnw dependency:tree -Dincludes='org.bouncycastle' | grep -E '1.78.1' | wc -l
45
```

Update Bouncycastle to 1.78.1 for CVE-2023-33201

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

This adds an entry to version-info that the UI can display to ensure OSS and PRO UI shows product name and version differently.
In Pro the entry has the following:
```yaml
spring-cloud-dataflow-server:
name: Spring Cloud Dataflow Pro Server
```            
in OSS:
```yaml
spring-cloud-dataflow-server:
name: Spring Cloud Dataflow Server
```

Add spring-cloud-dataflow-server to version-info.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/UiController.java

- Boot 3.x changed handling of trailing slash meaning it's now adviced to define both /dashboard and /dashboard/ in UiController
Essentially to fix latter:
```
jvalkealahti@cypher:/tmp/xxx$ http --headers http://localhost:9393/dashboard
HTTP/1.1 302 
Connection: keep-alive
Content-Language: en-GB
Content-Length: 0
Date: Mon, 13 May 2024 12:36:17 GMT
Keep-Alive: timeout=60
Location: http://localhost:9393/dashboard/index.html
jvalkealahti@cypher:/tmp/xxx$ http --headers http://localhost:9393/dashboard/
HTTP/1.1 500 
Connection: close
Content-Type: application/hal+json
Date: Mon, 13 May 2024 12:36:21 GMT
Transfer-Encoding: chunked
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
```

Add trailing slash to dashboard

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java

ThinTaskExecutions are not a part of SCDF-3.0.x.
During the migration some of the ThinTaskExecution URL calls were left in the rest client and this caused some test failures in IT. This PR removes the API access from the client for ThinTaskExecutions.

Remove thinTaskExecutionList from TaskTemplate

---

spring-cloud-dataflow-aggregate-task/src/main/java/org/springframework/cloud/dataflow/aggregate/task/impl/DefaultAggregateTaskExplorer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

The full list was retrieved for each task instead of queries by schema.
Also found test that weren't executed and changed `@Nested` to `static` classes.

last task execution performance

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-skipper/pom.xml

Update various lib deps patch versions
- netty to 4.1.111.Final
- reactor-bom to 2020.0.45
- jackson-bom to 2.17.2
- nimbus-jose-jwt to 9.37.3
- testcontainers to 1.19.8
Also removes unnecessary dependency management.

Update various lib deps patch versions 

---

spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-single-step-batch-job/pom.xml

This change is only for the Single Step Batch Job and Composed Task Runner.

Remove Dependency Mgmt for H2 and rely on Boot Bom

---

spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseReportService.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/util/ArgumentSanitizer.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/util/ManifestUtils.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/BaseDocumentation.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/ConfigValueUtilsTests.java
spring-cloud-skipper/spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/ManifestCommands.java
spring-cloud-skipper/spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/io/DefaultPackageReader.java
spring-cloud-skipper/spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/io/DefaultPackageWriter.java
spring-cloud-skipper/spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/io/PackageMetadataSafeConstructor.java
spring-cloud-skipper/spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/support/yaml/DefaultYamlConverter.java
spring-cloud-skipper/spring-cloud-skipper/src/test/java/org/springframework/cloud/skipper/io/PackageMetadataSafeConstructorTests.java
spring-cloud-skipper/spring-cloud-skipper/src/test/java/org/springframework/cloud/skipper/io/PackageWriterTests.java

Use root provided to determine type of conversion to use.
* Added tests when root is specified
* Added tests for builder
Remove PackagMetadataBuilder, it is not needed
Update default constructors to use the safe constructor.

Ensure PackageMetadata is created with SafeConstructor

---

src/kubernetes/mariadb/mariadb-deployment.yaml
src/kubernetes/mysql57/mysql-deployment.yaml

Fix **mariadb** and **mysql** deployment to ensure `dataflow` and `skipper` databases are created.
Fixes #5876

Fix mariadb and mysql deployment to create databases

---

.github/workflows/ci.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/tasks/TaskExecutionQueryContainer.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/Oracle_XE_18_SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/support/DatabaseTypeTests.java
spring-cloud-skipper/spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/db/migration/Oracle_XE_18_SkipperSmokeTest.java

Fix issue with large Oracle container causing disk space issue by running DB2 and Oracle specific tests in separate parallel jobs.
Found the following in ci and build-snapshot-worker logs.
```
##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 20 MB
```

Fix problem with large Oracle container causing disk space issue

---

src/carvel/test/servers.test.ts
src/deploy/carvel/configure-prometheus-proxy.sh
src/docker-compose/docker-compose-influxdb.yml
src/templates/docker-compose/docker-compose-influxdb.yml

> [!NOTE]
> Ignore the 1st commit as this PR is based from https://github.com/spring-cloud/spring-cloud-dataflow/pull/5888
In Boot 3.x metrics names have switched from `management.metrics.export.<registry>` to `management.<registry>.metrics.export`. Most of these references have already been adjusted (e.g. https://github.com/spring-cloud/spring-cloud-dataflow/commit/21f59888bf8e13ae85a5c09be3586f70367e87cc) but there were a few stragglers that still needed this treatment. Enter stage left, commit 2 and 3.

Update remaining occurrences of Boot 2.x metric prop names

---

src/carvel/config/dataflow.lib.yml
src/carvel/config/skipper.lib.yml
src/kubernetes/server/server-config.yaml
src/templates/kubernetes/server/server-config.yaml

The previous commits for updating metric names to the Boot 3.x format missed some entries in yaml files. 
This commit updates the yaml files.

Update metric prop names in yaml files

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractDatabaseTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/MariadbSharedDbIT.java

This commit re-enables the `MariadbSharedDbIT` and disables the Java 21 test variant as Java 21 container images are not yet supported.

Enable MariadbSharedDbIT

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

Updates the following:
- Spring Framework to 5.3.39
- Tomcat to 9.0.93
- Netty to 4.1.113.Final
- Reactor to 2020.0.47
- Snappy Java to 1.1.10.6
> [!NOTE]
> I chose to keep these in a single commit as they are not CVE related. I will update the release notes accordingly

Update various dependencies patch versions

---

src/docker-compose/docker-compose-wavefront.yml
src/docker-compose/docker-compose-zipkin.yml

This commit adds the global tracing property
'management.tracing.enabled' to the Zipkin and Wavefront docker compose files.
Also, the Wavefront docker compose file excludes the Zipkin tracing auto-configuration and the Zipkin docker compose file excludes the Wavefront tracing auto-configuration.

Fix tracing properties in docker compose

---

src/deploy/k8s/configure-k8s.sh
src/deploy/k8s/set-ver.sh
src/deploy/k8s/use-gke.sh
src/deploy/k8s/use-microk8s.sh
src/deploy/k8s/use-mk.sh
src/deploy/k8s/use-tmc.sh

Updated k8s setup scripts to improve consistency in options available to various use-* scripts for initializing the BROKER, DATABASE, NS and other kubectl related configuration.

[CI] Improve k8s setup scripts.

---

spring-cloud-dataflow-platform-kubernetes/src/main/resources/META-INF/spring.factories

These autoconfigurations have already been moved to the spring/org.springframework.autoconfigure.AutoConfiguration.imports file

Remove unused spring.factories in the spring-cloud-dataflow-platform-kubernetes

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/DataflowTaskExplorerConfiguration.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/LocalConfigurationTests.java

Currently if the user sets task-enabled to false SCDF will fail to start.
* Rename DataflowTaskConfiguration to DataflowTaskExplorerConfiguration so that it expresses its usage. 
* Rename aggregateTaskExplorer to dataflowTaskExplorer 
* Set the `ConditionalOnTasksEnabled` annotation so that the configuration won't fire if `task-enabled` is set to false. 
* Remove the `Disabled` annotation from the test so that we can verify that the `task-enabled` works properly.

Allow users to disable task features in dataflow

---

spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/test/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/CommandTests.java

This test still fails sporadically

Re-enable for CommandTest

---

spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/main/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DefaultDockerCompose.java
spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/main/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DockerComposeVersion.java
spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/test/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DockerComposeVersionTests.java
spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/test/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DockerTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java
spring-cloud-skipper/spring-cloud-skipper-autoconfigure/src/main/java/org/springframework/cloud/skipper/server/autoconfigure/CloudFoundryPlatformAutoConfiguration.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/PackageService.java

Replace deprecated Version.valueOf with Version.parse

---

.github/workflows/ci-pr.yml
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/ApiDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration.adoc
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionThinController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/TaskDefinitionRepository.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/impl/DefaultDataFlowTaskExecutionQueryDao.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/resources/root-controller-result.json
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/tasks/AbstractLargeTaskExecutionDatabaseBase.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java

Change TaskTemplate to use task/thinexecutions instead of task/executions.
Add task thin executions by name.
Update api-guide.adoc with links to generated documentation.
Modify TaskCommands to use thin executions since it provides the data required.
Removed duplicate entries from api docs.
Fixes #5991
Fixes #5973

Add task thin executions by name and fix missing docs.

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-dependencies-parent/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-rest-resource/pom.xml
spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-shell-core/pom.xml
spring-cloud-skipper/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server/pom.xml
spring-cloud-skipper/spring-cloud-skipper/pom.xml

This commit does the following:
- Removes versions on dependencies that are already managed by boot
- Pulls version numbers into the root pom.xml
- Removes some unused properties and dependencies
> [!IMPORTANT]
> The goal of this PR is to update the versions and remove any unnecessary cruft (dep mgmt, versions, etc..). However, once we get this done I plan on reducing the parentage down to a single one rather than the 2 we have now. If we don't do it now, we never will. 
> [!NOTE]
> I have painstakenly run dep tree on each of the libs in question to ensure there is only a single version and that version is the latest w/o CVEs. For example:
> ```
> DEP="org.apache.commons:commons-compress"
> ./mvnw dependency:tree -Dincludes="$DEP" | grep -E "$DEP"
> ```
> Yields
> ```
> [INFO]       \- …
```

Update to Spring Boot 3.3.5 and cleanup deps

---

spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/job/StepExecutionHistory.java

Update api-guide to remove deprecation notice
Also polish documents to remove errors.
The original intent was to remove these calls from the Rest request as it was not actively used.
But after discussions, we decided to retain this feature.
Resolves #6015

Remove deprecation annotation from StepExecutionHistory.java

---

src/scripts/build-docs.sh

Updates build-docs.sh path usage to execute in project root.

Fix build-docs.sh error

---

spring-cloud-skipper/spring-cloud-skipper/src/main/java/org/springframework/cloud/skipper/domain/CloudFoundryApplicationManifestReader.java

This is the recommended replacement for the deprecation

Replace deprecated YamlMapper configure methods to use its builder

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
src/carvel/config/values/values.yml
src/carvel/docs/configuration-options.adoc
src/deploy/carvel/load-images.sh
src/deploy/images/pull-prometheus-rsocket-proxy.sh
src/deploy/k8s/deploy-scdf.sh
src/docker-compose/docker-compose-prometheus.yml
src/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
src/templates/docker-compose/docker-compose-prometheus.yml
src/templates/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml

This commit updates the Prometheus Rsocket Proxy dependency and Docker images used in the installers to 2.0.0-M2.
See #6069

Update to Prometheus RSocket Proxy 2.0.0-M2

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/ApiDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionThinController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/TaskDefinitionRepository.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/resources/root-controller-result.json

Updates api docs for tasks/thinexecutions/name and all HATEOAS links. Updates related tests for links. Improved link handling and tests in TaskTemplate.
Original PR #5994 
Issues #5991, #5973
Fixes #5995

Back port of Task Thin Execution List and List By Name

---

.github/workflows/ci.yml

Adds an input flag `enableSecurityScan` that is false by default and will only include the scan job if set to true.

Disable Trivy by default

---

.github/workflows/ci-pr.yml
.github/workflows/ci.yml

Added env to control the scan.
Added env to identify alternate repo.

Provide for disabling security scan in ci-pr.yml and adding alternative repo

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/cental-sync.yml
.github/workflows/central-release.yml
.github/workflows/ci.yml
.github/workflows/milestone-worker.yml
.github/workflows/next-dev-version-worker.yml
.github/workflows/promote-milestone.yml
.github/workflows/promote-release.yml
.github/workflows/publish-docs.yml
.github/workflows/release-worker.yml

Update setup-jfrog-cli to use `JF_ENV_SPRING` instead of `JF_ARTIFACTORY_SPRING` 
Added `JF_URL`
Added reference to `${{ vars.JF_SERVER_ID }}` in place of `repo.spring.io`
**NOTE**: The branch was labeled with -main but was actually branched from 2.11.x

[CI] Update jfrog cli to v3

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractPostgresDatabaseTests.java

Adds `@Disabled` to migration testing backwards compatibility
The backwards compatibility between 2.10 and 2.11 can be tested easily, but between 2.11 and 3.0 will not work because the dataflow client of 3.0 cannot interact with 2.11
So we can only start doing these types of tests when we have 3.0 and 3.1

Disable test for backwards compatibilty in DB IT

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-tasklauncher/spring-cloud-dataflow-tasklauncher-sink-dependencies/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml
src/carvel/config/values/values.yml
src/carvel/docs/configuration-options.adoc
src/deploy/carvel/load-images.sh
src/deploy/images/pull-prometheus-rsocket-proxy.sh
src/deploy/k8s/deploy-scdf.sh
src/docker-compose/docker-compose-prometheus.yml
src/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
src/templates/docker-compose/docker-compose-prometheus.yml
src/templates/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml

Replaces the `micrometer.io:micrometer-registry-prometheus-simpleclient` with `micrometer.io:micrometer-registry-prometheus`.
Also updates the Prometheus RSocket version from `2.0.0-M3` to `2.0.0-M4`.
See #6068
See #6069

Use new Prometheus RSocket client
