pom.xml
spring-cloud-data-rest/pom.xml
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/repository/StreamDefinitionRepository.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/repository/StubStreamDefinitionRepository.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/AdminApplication.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/config/AdminConfiguration.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/controller/AdminController.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/controller/StreamController.java
spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/resource/StreamDefinitionResource.java

* REST API configured for JSON only support
* Supports basic shell functionality (stream list and create)
* Added management.contextPath property

REST API controller

---

spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/controller/StreamController.java

to test this with xd-shell, build it after modifying `SpringXDTemplate` to exclude all resources and operations that are not related to streams, e.g.:
```
public SpringXDTemplate(ClientHttpRequestFactory factory, URI baseURI, String rabbitMqAdminUri,
String rabbitMqPassword, String rabbitMqUsername, String rabbitMqVhost, String busPrefix) {
super(factory);
XDRuntime xdRuntime = restTemplate.getForObject(baseURI, XDRuntime.class);
resources.put("streams/definitions", new UriTemplate(xdRuntime.getLink("streams").getHref() + "/definitions"));
resources.put("streams/deployments", new UriTemplate(xdRuntime.getLink("streams").getHref() + "/deployments"));
//		resources.put("jobs", new UriTemplate(xdRuntime.getLink("jobs").getHref()));
//		resources.put("jobs/definitions", new …
```

added deploy, undeploy and 'destroy support

---

spring-cloud-data-rest-client/src/main/java/org/springframework/cloud/data/rest/client/CloudDataClientException.java
spring-cloud-data-rest-client/src/main/java/org/springframework/cloud/data/rest/client/CloudDataTemplate.java
spring-cloud-data-rest-client/src/main/java/org/springframework/cloud/data/rest/client/StreamOperations.java
spring-cloud-data-rest-client/src/main/java/org/springframework/cloud/data/rest/client/StreamTemplate.java
spring-cloud-data-rest-client/src/main/java/org/springframework/cloud/data/rest/client/VndErrorResponseErrorHandler.java
spring-cloud-data-rest-resource/src/main/java/org/springframework/cloud/data/rest/util/DeploymentPropertiesUtils.java
spring-cloud-data-shell/src/main/java/org/springframework/cloud/data/shell/command/ConsoleUserInput.java
spring-cloud-data-shell/src/main/java/org/springframework/cloud/data/shell/command/StreamCommands.java
spring-cloud-data-shell/src/main/java/org/springframework/cloud/data/shell/command/UserInput.java
spring-cloud-data-shell/src/main/java/org/springframework/cloud/data/shell/config/CloudDataShell.java
spring-cloud-data-shell/src/main/java/org/springframework/cloud/data/shell/util/Assertions.java

- deploy
- undeploy
- undeploy all
- destroy
- destroy all

added support for remaining stream operations

---

spring-cloud-data-rest/src/main/java/org/springframework/cloud/data/rest/AdminApplication.java
spring-cloud-data-rest/src/main/resources/application.yml

- Set default properties in `application.yml`
- This will also enable injecting overriding properties via `args`

Add admin config file

---

spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-local/pom.xml
spring-cloud-data-module-deployers/spring-cloud-data-module-deployer-local/src/main/java/org/springframework/cloud/data/module/deployer/local/LocalModuleDeployer.java

We need to add security for the endpoints at the level of ModuleLauncher, but for now the /shutdown endpoint is only enabled for local deployment anyways.

XD-3344 LocalModuleDeployer uses shutdown endpoint

---

spring-cloud-data-admin/pom.xml
spring-cloud-data-admin/src/main/resources/META-INF/spring-cloud-data-admin/admin.properties
spring-cloud-data-admin/src/main/resources/bootstrap-yarn.yml

- Move yarn specific config from admin.properties to `bootstrap-yarn.yml` so that these config will only be loaded when `yarn` profile is active.

Yarn profile based config

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/DataFlowServerException.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/DataFlowTemplate.java
spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java

JIRA: https://jira.spring.io/browse/XD-3701
Provide a meaningful message/log when we can connect, but can't parse the response.

XD-3701: Shell Admin Parse Errors

---

spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/spring-cloud-dataflow-overview.adoc

This PR includes changes to SCDF introduction section and links.

Update overview section

---

spring-cloud-dataflow-admin-starter/src/main/java/org/springframework/cloud/dataflow/admin/controller/StreamDeploymentController.java

- When the DSL has `module.<label>.producer/consumer.` properties, then they need to be set as `spring.cloud.stream.producer/consumerProperties`.
- The partition properties also need to be updated per binding case.
- This fixes #264

Fix passing producer/consumer properties

---

spring-cloud-dataflow-admin-starter/src/main/java/org/springframework/cloud/dataflow/admin/config/ArtifactRegistryPopulator.java
spring-cloud-dataflow-admin-starter/src/main/java/org/springframework/cloud/dataflow/admin/controller/TaskExecutionController.java
spring-cloud-dataflow-admin-starter/src/test/java/org/springframework/cloud/dataflow/admin/repository/TaskExecutionExplorerTests.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskExecutionResource.java
spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java
spring-cloud-dataflow-shell/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTests.java

* Removes the statusCode and externalExecutionId
* Adds timestamp task back to ArtifactRegistryPopulator
Resolves spring-cloud/spring-cloud-dataflow#331

SCDF-331 Removes Unused Task Columns

---

pom.xml

SCDF should be using M1 milestone and not snapshot.

Set SCDF to use Milestone vs snapshot.

---

pom.xml
spring-cloud-dataflow-completion/pom.xml

* Now comes from scs-dependencies bom
Partially fixes #384

GH-384 Remove explicit dependency on scs-config-metadata version

---

spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-server-local/pom.xml
spring-cloud-starter-dataflow-server-local/pom.xml

This reverts commit ca0770e019ab30640a829126f24fcc53c6becdb0.
This reverts commit 766e4635e97517e8c3f6da6591fbc4effb3b9318.
This reverts commit 5c07e832f237e670e6f5297b72a5bc0a94f5085d.

Revert "starter jar->pom" change

---

spring-cloud-dataflow-app-launcher/src/main/java/org/springframework/cloud/dataflow/app/resolver/AetherModuleResolver.java
spring-cloud-dataflow-app-launcher/src/main/java/org/springframework/cloud/dataflow/app/resolver/MavenProperties.java

Use `maven.` prefix for resolver properties

---

spring-cloud-dataflow-deployer-local/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java
spring-cloud-dataflow-server-local/pom.xml
spring-cloud-dataflow-server-local/src/main/resources/dataflow-server.yml

- Move from `deployer-local`
- as its name suggests the yml file should belong to server-local
- Also remove `@EnableConfigurationProperties(MavenProperties.class)` in DataFlowServerConfiguration as this properties should belong to deployer configuration
This resolves #445

Move dataflow-server.yml to server-local

---

spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDeploymentController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/registry/DataFlowUriRegistryPopulator.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/registry/DataFlowUriRegistryPopulatorProperties.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/registry/RedisUriRegistry.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/applications.properties
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

also populating the registry on startup by default
(with "locations" and "enabled" as boot properties of the populator)
The DelegatingResourceLoader includes:
- MavenResourceLoader for 'maven:'
- DefaultResourceLoader for 'file:' and 'http:'

use UriRegistry in deployment controllers

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java

- assuming status is undeployed when deployment id is null
Fixes #499

Adding null check for deployment id

---

README.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/spring-cloud-dataflow-overview.adoc

updated dataflow docs and links

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/ModuleController.java

- cathcing exception from Docker URIs
- need to figure out properties later (TODO)
Fixes #560

Fix module info for Docker apps

---

spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/ModuleCommands.java
spring-cloud-dataflow-shell/src/test/java/org/springframework/cloud/dataflow/shell/command/ModuleCommandsTests.java

Fix NPE when module info doesn't exist

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java

- Since Dataflow UI expects the `DefaultRelProvider` to be used, always override the RelProvider with the DefaultRelProvider

Override EvoInflectorRelProvider with DefaultRelProvider

---

spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/UiController.java

Requires: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/32
Resolves spring-cloud/spring-cloud-dataflow#646

gh-646 Server: Change `/admin-ui` -> `/dashboard`

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskExecutionResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDeploymentController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java
spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java
spring-cloud-dataflow-shell/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTests.java

* Change `TaskExecutionResource#parameters` to `arguments`
resolves spring-cloud/spring-cloud-dataflow#649

gh-649 Tasks: Change Parameter to Arguments

---

spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-registry/pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-starter-dataflow-server-local/pom.xml

- This way we only need to specify the version at the dependencies pom
This resolves #657

Add spring-cloud-deployer dependencies into dataflow deps

---

spring-cloud-dataflow-server-local/src/main/resources/META-INF/task-apps.properties

Resolves spring-cloud/spring-cloud-dataflow#678

Remove Sqoop tasks from the registry

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/apps/CommonApplicationProperties.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java

Resolves spring-cloud/spring-cloud-dataflow#661

GH-661 Add support for passing global properties to applications

---

spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommands.java

Change --name to --id.

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/DSLMessage.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/StreamParser.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/StreamParserTests.java

- Stream name can be one of the app names
- Add test
- Remove existing error check and DSL message
This resolves #700

Support app name as stream name

---

spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc

Fixes spring-cloud/spring-cloud-dataflow-server-cloudfoundry#121

Allow skipping of tasks related docs

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml

* Remove spring boot dependency declaration

Move dependencies from parent pom to dependencies bom

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/DataFlowAppDefinition.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java

properly allocate deployment and app properties

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Fix doc error

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java

remove `count` as a property from app properties

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Resolves spring-cloud/spring-cloud-dataflow#751

gh-751 Document that only boot 1.3.x apps support property whitelisting

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/StreamAppDefinition.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/TaskDefinition.java
spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/apps/package-info.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/support/package-info.java
spring-cloud-dataflow-shell/src/main/java/org/springframework/cloud/dataflow/shell/ShellCommandLineParser.java

- Also, add package-info for a package
This resolves #776

Fix javadoc warnings

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentControllerTests.java
spring-cloud-dataflow-server-core/src/test/resources/apps/whitelist-source/META-INF/spring-configuration-metadata.json

Fixes spring-cloud/spring-cloud-dataflow#779

Accept relaxed variations when expanding short props

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Fix doc for white-list properties

---

pom.xml

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/819

gh-819 Enable Sonar Builds + JaCoCo Code Coverage

---

spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Fixes spring-cloud/spring-cloud-dataflow/issues/861

Fix generated links in reference docs

---

spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Fixes spring-cloud/spring-cloud-dataflow/issues/861

[1.0.x] Fix generated DL links in reference docs

---

pom.xml
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/BootClassLoaderFactory.java

Fixes spring-cloud/spring-cloud-dataflow/issues/887

Upgrade to boot 1.4

---

spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Upgrade SCT dependencies to 1.1.M1.

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml

Update Spring Framework, Boot and Cloud dependencies

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskExecutionResource.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTemplate.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTests.java

resolves #823
* task display renamed to task execution status
* removed task status
* Updated tests
* added error message field to task execution status

Shell: UX issue - standardize task commands

---

spring-cloud-dataflow-dependencies/pom.xml

Update to use SCDe 1.1.0.BUILD-SNAPSHOT

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Doc for per-binding producer consumer SCSt properties

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/AbstractTaskDefinitionTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/InMemoryTaskDefinitionRepositoryTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/RdbmsTaskDefinitionRepositoryTests.java

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/952

gh-952 Add Tests Ensuring Sorting Works for Task Definitions

---

spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/StreamCommands.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/StreamCommandTemplate.java

Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/954

Change stream create+deploy success message

---

pom.xml

- Also use local deployer 1.1.1.RELEASE
- Fixes #1035

Upgrade to SCDe 1.1.1.RELEASE

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml
spring-cloud-dataflow-server-local/src/main/java/org/springframework/cloud/dataflow/server/local/LocalDataFlowServer.java
spring-cloud-dataflow-server-local/src/main/java/org/springframework/cloud/dataflow/server/local/LocalDataFlowServerConfiguration.java

- Add docker resource loader into DelegatingResourceLoader bean for `local` data flow server configuration
This resolves #695

Support deploying docker apps in local data flow server

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/Tokenizer.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/StreamParserTests.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/TaskParserTests.java

Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/923

Throw parse error on unbalanced quotes in string literals

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java

Show full stack trace on errors deploying apps

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

Update to spring-cloud-task 1.1.1.RELEASE

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

Update to spring-cloud-task 1.1.2.RELEASE

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/web/WebConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/CompletionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/CompletionControllerTests.java

* Use JSR303 bean validation to validate method parameters (`@RequestParam`)
* Enable bean validation by adding a `MethodValidationPostProcessor` to `WebConfiguration`
* Add tests
Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1073

gh-1073 Completion Controller - Fix Able to provide negative detail level

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommands.java

- When the application info is queried, non existent app should throw appropriate exception i.e, NoSuchAppRegistryException
- Update AppRegistry command to handle the exception appropriately
- Add test
Resolves #1070

Error handling on non existent app

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/security/SecurityInfoResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/security/SecurityController.java

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1158

gh-1158 Provide the User-associated roles via the `/security/info`

---

pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-local/pom.xml

Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/1164
This is a PR against 1.1.x that should also be commited to master (paying attention not to override versions)

Leverage MultiStateAppDeployer in StreamDefController

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

Remove unecessary spring-cloud-deployer-resource-docker dependency

---

spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/AddAppOptionsExpansionStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/AddAppOptionsTaskExpansionStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ConfigurationPropertyNameAfterDashDashRecoveryStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ConfigurationPropertyNameAfterDashDashTaskRecoveryStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ConfigurationPropertyValueHintExpansionStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ConfigurationPropertyValueHintRecoveryStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ConfigurationPropertyValueHintTaskExpansionStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ConfigurationPropertyValueHintTaskRecoveryStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/UnfinishedConfigurationPropertyNameRecoveryStrategy.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/UnfinishedConfigurationPropertyNameTaskRecoveryStrategy.java
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/ApplicationConfigurationMetadataResolver.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/WhitelistProperties.java

- retrieve metadata resource from AppRegistry when listing properties
- update code completion/app info registry controller classes
Resolves #1137

Use MetadataResource when listing properties

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Update docs to include Avogadro.SR1

---

spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/ApplicationConfigurationMetadataResolver.java
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolver.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java

Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/1185

Correctly use *app* resource when launching. Dont fail on unreadable resources

---

pom.xml

Update snapshot version for deployer/UI

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/1163

Document the new deployer. vs app. split

---

pom.xml
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/DefaultValueHintProvider.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/security/OnSecurityEnabledAndOAuth2DisabledTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/security/OnSecurityEnabledAndOAuth2EnabledTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-local/pom.xml
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithLdapSimpleBindAndDefaultManagementTests.java

Adapt to changes in Boot:
- package changes
- changes around Hints
- changes in BatchDatabaseInitializer
- security fixes for actuator
Resolves #1168

Update to Spring Boot 1.5.2 and Dalston

---

spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AboutController.java
spring-cloud-dataflow-server-local/pom.xml
spring-cloud-starter-dataflow-server-local/pom.xml

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1243

gh-1243 GitProperties shown should be for the SCDF Implementation

---

spring-cloud-dataflow-docs/src/main/asciidoc/howto.adoc

Inadvertently fixed a bunch of trailing spaces too.

Fix link to local deployer (DEBUG logs)

---

pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java
spring-cloud-dataflow-server-local/pom.xml

Resolves #1266 
Depends on https://github.com/spring-cloud/spring-cloud-task/pull/299

Adding taskName when creating new TaskExecution

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskDefinitionResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/TaskService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/services/impl/DefaultTaskServiceTests.java

- store original dsl
- calculate executable graph on launch
- calculate composed indicator when creating TaskDefinitionResource
Resolves #1313

Add composed task indicator to TaskDefinitionResource

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

* Spring Cloud Dalston RELEASE
* Spring Cloud Deployer 1.2 RC1
* Spring Cloud Deployer Local 1.2 RC1
Fixes #1324 and #1315

Upgrade dependencies

---

spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

* Also added docs on  stopping tasks and the notes on its behavior when restarting a stopped CT
* Added note that bulk load for composed tasks is not supported

Adding docs for restarting composed tasks

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/support/MetricStore.java

Changing metrics request logging to WARN

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

Update to GA versions of spring-cloud-deployer and spring-cloud-task

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/AppRegistryTemplate.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/JobTemplate.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeTemplate.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/StreamTemplate.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java

- revert commit 21840685925dc9272f86c0fc054f0c63e51208c4
- revert commit eae98f4065eca66c89482bf249761f0a0c19d8e6
These pagination changes will be made after 1.2.0 GA

Revert changes made in PR #1383

---

spring-cloud-dataflow-completion/src/test/java/org/springframework/cloud/dataflow/completion/Expresso.java
spring-cloud-dataflow-completion/src/test/support/boot13/src/main/java/com/acme/boot13/AnotherEnumClass13.java
spring-cloud-dataflow-completion/src/test/support/boot14/src/main/java/com/acme/boot14/AnotherEnumClass14.java
spring-cloud-dataflow-completion/src/test/support/common/src/main/java/com/acme/common/SomeEnum.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/DSLMessage.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/TokenKind.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/AggregateCounterOperations.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/DeploymentStateResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/security/support/CoreSecurityRoles.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/job/support/StepExecutionProgressInfo.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/support/DatabaseType.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/support/Order.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/Target.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/support/OpsType.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/support/RoleType.java
src/eclipse/eclipse-code-formatter.xml

- Fix code format rule for enum constants
- Apply formatting changes
Resolves #1425

Fix enum formatting

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Fix task transition symbol rendering in PDF

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

- at the section where `snapshot` is referred

Doc fix - use snapshot version

---

spring-cloud-dataflow-server-local/src/main/resources/application.yml

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1446

gh-1446 Provide role-property example in `application.yml`

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1459

gh-1459 Docs: Fix Admonitions

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Downgrading task apps links in docs from Belmont GA to RC1

---

spring-cloud-dataflow-dependencies/pom.xml

Update version of spring-cloud-dependencies-parent to 1.3.1

---

.travis.yml
README.adoc
pom.xml

- update travis yml
- add cobertura-maven-plugin update
- Update banner image in doc for `master` branch
Resolves #1480

Add codecov

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-server-local/pom.xml

- for `spring-cloud-dataflow-dependencies` and `dataflow-server-local`
Resolves #1520

Update to snapshot versions

---

spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/BaseDocumentation.java
spring-cloud-dataflow-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/RuntimeAppsDocumentation.java

Document REST endpoint for RuntimeAppsController

---

.travis.yml

Force dedicated vm on travis

---

pom.xml

Resolves spring-cloud/spring-cloud-dataflow#1565

Update UI dependency to `1.2.1.RELEASE`

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

Update Spring Cloud Task version to 1.2.1.RELEASE

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/dsl/DestinationNode.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/dsl/NodeTests.java

- fixed the toString() of DestinationNode
- minor code polishing in DestinationNode
- added tests to validate the reported behavior

GH-1568 fixed the toString()

---

pom.xml

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1621

gh-1621 Update the Spring Cloud Data Flow UI dependency to `1.3.0.BUILD-SNAPSHOT`

---

spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc

Resolves reference doc images from 1.2.x branch

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

- Doc to show how to update snapshot/release update policies for the remote repository configuration
Resolves #1645

Add doc for maven repo policies configuration

---

pom.xml

Update spring-cloud-deployer to 1.3.0.M1

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployerTests.java

Add support for extracting docker resource with and without version

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

Resolves spring-cloud/spring-cloud-dataflow#1718

Make stream update endpoint to accept any path occurrence

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java

Add kind,apiVersion to generated packages

---

pom.xml

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1727

gh-1727 Update Spring cloud Data Flow UI dependency to 1.3.0.M3

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AppDeploymentRequestCreator.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceUpgradeStreamTests.java
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests-install.yml
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/TaskCommands.java

Add `version` as a level deployment property in skipper commands

---

README.adoc

- Add reporting-issues wiki link
- Update project description
- Replace module reference to application

General README updates

---

pom.xml
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-local-autoconfig/pom.xml

Adding dependencies to modules

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

- spring-cloud-build to 1.3.6
- boot to 1.5.8
- spring-cloud to Edgware.RELEASE
- same changes for spring-cloud-dataflow-server-local
- Fixes #1796

Update dependency versions

---

spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommands.java

Display app version only in Skipper mode

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/ToolsControllerTests.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithSingleUserTests.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithUsersFileTests.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1864

gh-1864 HttpMessageNotReadableException should not return a 500 HTTP status code

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AbstractStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AppDeployerStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/SkipperStreamService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentControllerTests.java

- Remove overhead on calling doState() and use state() instead
- Minor cleanup

Refactor StreamService

---

spring-cloud-dataflow-server-core/pom.xml

Added exclusions for jackson and FreeMarker for Spring batch admin

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java

Renames Skipper's AboutInfo to AboutResource in SCDF

---

pom.xml

- Skipper -> RC1
- Common security config -> RC2
Resolves #1961

Update Skipper/common security config to RC

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/1978

gh-1978 Fix RootController shows invalid value for AppInstanceController

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientProperties.java

Renaming uri field

---

pom.xml

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2026

gh-2026 Upgrade Dashboard UI to `1.3.0.RELEASE`

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/AppDeployerStreamDeployer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/StreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsControllerSkipperTests.java

- fix the pagination format of the runtime app controller response
- update tests
Resolves #2037

Runtime App Controller Pagination error

---

spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithSingleUserTests.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithUsersFileTests.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/security/LocalServerSecurityWithUsersFileTestsWithoutTasks.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2066

gh-2066 Tests: Replace Bitly links with direct repo links

---

spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc

Resolved ascii-doc issue.

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/StreamDefinitionToDslConverter.java
spring-cloud-dataflow-core/src/test/java/org/springframework/cloud/dataflow/core/StreamDefinitionToDslConverterTests.java

StreamDefinitionToDslConverter produces invalid DSL

---

spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Parameterize wget command in docker-compose.yml

---

spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/DockerImage.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/ResourceUtils.java
spring-cloud-dataflow-registry/src/test/java/org/springframework/cloud/dataflow/registry/support/DockerImageTests.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSkipperStreamServiceUpdateTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/stream/ResourceUtilsTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/PlatformUtils.java

- Use DockerImage utility class to parse parts of docker resource
- Add quick hack wrt to return character failing test on windows
- Had to reformat some test files as checkstyle was failing
Fixes #2107

Docker Resource with host name isn't recognized

---

pom.xml

- Needed to get metrics working with local server
as there are a bending change in local deployer.

Update to local deployer 1.3.4.BUILD-SNAPSHOT

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Corrected formatting

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/HttpClientConfigurer.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/resource/HttpClientTest.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/util/HttpClientConfigurerTests.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/support/MetricStore.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/common/ConfigCommands.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/common/HttpCommands.java

* Add tests
resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2130

gh-2130 Fix SCDF shell authentication does not work when accessing SCDF behind the proxy

---

pom.xml

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2151

gh-2151 Update Dashboard dependency to 1.5.0.M2

---

pom.xml
spring-cloud-dataflow-server-local/pom.xml

Upgrade Spring boot to 1.5.13

---

pom.xml

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2207

gh-2207 Update Dashboard Dependency to 1.5.0.RELEASE

---

spring-cloud-dataflow-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java

Fixes Doc's tests for #1826

---

spring-cloud-dataflow-server-local/src/main/java/org/springframework/cloud/dataflow/server/local/LocalDataFlowServer.java

Observed that exclude in yaml was not always respected

Add (exclude = SessionAutoConfiguration.class) to main class

---

spring-cloud-dataflow-server-local-autoconfig/src/main/java/org/springframework/cloud/dataflow/autoconfigure/local/LocalDataFlowServerAutoConfiguration.java
spring-cloud-starter-dataflow-server-local/src/test/java/org/springframework/cloud/dataflow/server/local/LocalConfigurationTests.java

Resolves #2262
- Remove the LRU resource delegation bean
- Fix the tests

Remove LRU for local SCDF server

---

pom.xml

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2294

gh-2294 Update UI dependency to 1.6.0.M1

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Update Celsius.SR2 apps to Celsius.SR3
Introduce Darwin.GA apps
Resolves #2210

Update stream app bit.ly URL's

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

- Skip the quote removal for input arguments
resolves #2242

Handle quotes in task launch arguments

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc
spring-cloud-dataflow-server-local/docker-compose.yml

Update Docker compose Kafka version

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/StreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AbstractStreamService.java

Streams Definitions search: update param name

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/DataFlowTemplate.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/StreamOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/StreamTemplate.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/common/AbstractStreamCommands.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/common/TaskCommands.java

Make client validation ops optional when connecting to older servers

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerServiceTests.java

Command line args not passed to ScheduleRequest

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskServiceTests.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2372

gh-2372 Implement audit-trail advice for TaskService

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/audit/domain/AuditOperationType.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AuditRecordControllerTests.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2480

gh-2480 Remove "App Registration" from AuditOperationType

---

spring-cloud-dataflow-server-core/src/main/resources/schemas/h2/jpa.sql
spring-cloud-dataflow-server-core/src/main/resources/schemas/mysql/jpa.sql
spring-cloud-dataflow-server-core/src/main/resources/schemas/postgresql/jpa.sql
spring-cloud-dataflow-server-core/src/main/resources/schemas/sqlserver/jpa.sql

Revert the uppercase jpa schema(s) done in the 960c8599358a691c3ff2786e58df485732015ea5 
Related to #2457

Revert the schema upper case changes done in #2457

---

spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/classic/ClassicAppRegistryCommands.java

- Make sure the app info cmd options are validated correctly
Resolves #2508

Fix app info cmd

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Update spring property delimiter in compose docs

---

pom.xml

Updated Spring Cloud Task Dependency to 1.3.1.RELEASE

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Update stream apps import bit.ly link to use Darwin-SR3

---

spring-cloud-dataflow-server-core/pom.xml

Add json-path dependency

---

spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryDataFlowServerConfiguration.java

Remove duplicate prefix on config properties bean

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc

- For maven properties
- For enable Local Platform in Skipper
Resolves #2714
Document the usage of CF Deployment properties for stream/task
- For stream (update Skipper)
- For task (update SCDF)
Resolves #2712

Document usage of SAJ for env properties

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

Added permissions for schedules instances

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/OnLocalPlatform.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-local-autoconfig/src/main/java/org/springframework/cloud/dataflow/autoconfigure/local/LocalSchedulerAutoConfiguration.java

Drop check on spring.cloud.dataflow.task.enableLocalPlatform property

---

spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformAutoConfiguration.java

- with IllegalStateException
Resolves #2804

Replace SkipperException at CF task platform config

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java

Resolves missing DSL in task detail request

---

spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc

Use Highlight JS instead of  prettify
Resolves #2825

Update documentation config

---

spring-cloud-dataflow-docs/src/main/asciidoc/architecture.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2872

gh-2872 Fix security-docs links in the reference guide

---

spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Added version to CTR maven URL example

---

spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java

- Remove `EnableCircuitBreaker` annotation from SCDF controller configuration
- Remove `hystrix` starter dependency
Resolves #2910

Remove circuit breaker configuration

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-dataflow-template.adoc

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/2853

gh-2853 Document the configuration of `DataflowTemplate` with OAuth's password-grant credentials

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java

Any property suffixed with 'url' will be redacted

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-building.adoc
spring-cloud-dataflow-registry/pom.xml
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfigurationTests.java
spring-cloud-dataflow-server/README.adoc
spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityWithUsersFileTests.java

Remove "spring-boot-starter-data-redis" dependency

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Update docs for enabling Kafka in Helm chart

---

Gemfile
README.markdown
_includes/download_widget.md
_sample-pages/project.html
_sample-pages/project_group.html
bootstrap/css/bootstrap-select.css
bootstrap/js/bootstrap-select.js
bootstrap/js/bootstrap.js
css/main.css.css
font-awesome/css/font-awesome-ie7.css
font-awesome/css/font-awesome.css
index.html
js/backbone.js
js/jquery.js
js/test/SpecRunner.html
js/test/lib/support/mock-ajax.js
js/test/spec/QuickStartWidgetSpec.js
js/underscore.js

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were unable to be fixed. Please review them to see if they can be manually resolved.
([https](https://erik.eae.net/archives/2007/07/27/18.54.15/) result SSLHandshakeException).
([https](https://javascript.nwbox.com/IEContentLoaded/) result SSLHandshakeException).
([https](https://blindsignals.com/index.php/2009/07/jquery-delay/) result SSLHandshakeException).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
https://fontawesome.com?from=io …

URL Cleanup

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Docs for Kubernetes Toleration support

---

spring-cloud-dataflow-dependencies/pom.xml

Upgrade to MariaDB connector 2.4.1

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskSchedulerController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskSchedulerControllerTests.java

Scheduled Task does not recognize multiple profiles

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-starter-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/security/LocalServerSecurityWithUsersFileTests.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/3267

gh-3267 Security: Add `/jobs/thinexecutions` security configuration

---

spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/AppResourceCommon.java
spring-cloud-dataflow-registry/src/test/java/org/springframework/cloud/dataflow/registry/support/AppResourceCommonTests.java

Handle  gracefully invalid resource URI schema

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java

Mainly used to select the proper http scheme in resource links when using SSL

Add ForwardedHeaderFilter to pass X-Forwarded-* headers

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-server/docker-compose-influxdb.yml
spring-cloud-dataflow-server/docker-compose.yml

- Update docker compose and docs to use latest app import links
Resolves #3288

Update app import links

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/3294

Revise K8s-deployer properties table to include the newly added properties

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Fix property name

---

spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/CompletionUtils.java
spring-cloud-dataflow-completion/src/main/java/org/springframework/cloud/dataflow/completion/ProposalsCollectorSupportUtils.java
spring-cloud-dataflow-core-dsl/src/main/java/org/springframework/cloud/dataflow/core/dsl/AppParser.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/DefinitionUtils.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/service/DefaultAppRegistryService.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/AppResourceCommon.java
spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/support/DockerImage.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/SimpleJobService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/job/support/StepExecutionProgressInfo.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtils.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/StreamDeployerUtil.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtilsTests.java
src/checkstyle/checkstyle.xml

Checkstyle cleanup for return count

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Document ConfigMap Key Ref support

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Docs for pod security context

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/TaskDefinitionRepository.java

resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/3351

gh-3351 Fix - Postgres: Task Search is not working

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/validation/DefaultTaskValidationService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

TaskValidation now handles invalid task definition name

---

spring-cloud-dataflow-registry/src/main/java/org/springframework/cloud/dataflow/registry/service/DefaultAppRegistryService.java
spring-cloud-dataflow-registry/src/test/java/org/springframework/cloud/dataflow/registry/service/DefaultAppRegistryServiceTests.java
spring-cloud-dataflow-registry/src/test/resources/org/springframework/cloud/dataflow/registry/service/AppRegistryTests-importAllOverwrite.properties
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java

- Return only the registered registrations
Resolves #3368

Fix importAll registrations

---

pom.xml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java

Fixed tests
Updated version number for spring-security-oauth2-autoconfigure
resolves #3414

Updated Task version to 2.2

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeTemplate.java

Fix the runtime apps app status URI

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/web/WebConfiguration.java

- This is for supporting cases like serving logfile endpoints
Resolves #3479

Add ResourceHttpMessageConverter into web configuration

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java

- Also, include pagination parameters
Resolves #3531

Fix AppRegistry REST doc for search request param

---

src/kubernetes/kafka/kafka-deployment.yaml
src/kubernetes/kafka/kafka-zk-deployment.yaml
src/kubernetes/mysql/mysql-deployment.yaml
src/kubernetes/rabbitmq/rabbitmq-deployment.yaml

Update k8s deployment configs to apps/v1

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc

Related to https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/322 
Depends on https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/323

Added description of 'autoDeleteMavenArtifacts

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/TaskManifest.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Remove SubTaskDeploymentRequest from Task execution manifest

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/DefinitionUtils.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/StreamDefinitionToDslConverter.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/TaskDefinitionToDslConverter.java

Ensure newlines escaped when recreating DSL from properties

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDeploymentsDocumentation.java
spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc

Document the Scale API

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration.adoc

- Fixes #3732
Depends on PR spring-cloud/spring-cloud-deployer#333

Add maven preemtive docs for wagon

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Updated so that validate and lock only occurs for CF Tasks

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Added docs for scheduling shell commands

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Resolves https://github.com/spring-io/dataflow.spring.io/issues/181

Resolves https://github.com/spring-io/dataflow.spring.io/issues/181

---

spring-cloud-dataflow-core-dsl/src/main/java/org/springframework/cloud/dataflow/core/dsl/visitor/ComposedTaskRunnerVisitor.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Checks to make sure any CTR split does not exceed maxConcurrentCount

---

spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

- Update doc on how commandline arguments are passed when `shell` EntyPointStyle is used.

Update entrypoint style doc

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Verify tasks running with TaskLauncher

---

pom.xml
spring-cloud-dataflow-shell-core/pom.xml
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/Target.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/ConfigCommandTests.java

- Conditionally use opaque or jwt token.
- Add support for using password grant with jtw tokens
in a shell.
- Relates #3748
- Relates #3827

Add jwt token support

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientProperties.java
spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientPropertiesTests.java

- Similar work done on a shell to be able to use bearer resolving
which is basically needed for jwt based setups.
- Relates #3748

Add bearer resolving to autoconfig

---

spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/container/DefaultContainerImageMetadataResolver.java
spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/container/authorization/DockerHubRegistryAuthorizer.java
spring-cloud-dataflow-configuration-metadata/src/test/java/org/springframework/cloud/dataflow/configuration/metadata/container/DefaultContainerImageMetadataResolverTest.java

Prevent RestTemplate parameters escaping

---

spring-cloud-dataflow-docs/pom.xml

Changed the doc-resources version to get Damien's latest look and feel.
Also changed the highlight to Github, as Damien suggests.

Updated doc-resources-version and highlight

---

spring-cloud-dataflow-autoconfigure/src/test/java/org/springframework/cloud/dataflow/autoconfigure/local/SchedulerPerPlatformTest.java
spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesSchedulerAutoConfiguration.java
spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformAutoConfiguration.java
spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformFactory.java
spring-cloud-dataflow-platform-kubernetes/src/test/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformFactoryTests.java

Verify that the use of this @Primary is correct
Only merge this after https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/380 has been merged.

Updated the imports to use the new package name for k8 schedules [WAIT TILL MERGE]

---

src/kubernetes/server/server-deployment.yaml
src/kubernetes/skipper/skipper-deployment.yaml
src/templates/kubernetes/server/server-deployment.yaml
src/templates/kubernetes/skipper/skipper-deployment.yaml

Add liveness/readiness probes

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java

This resolves #3894 Given DataFlowClientProperties `authentication.token-uri, authentication.client-id, authentication.client-secret` Will refresh the auth token whenever a request gets a 401 status.

Make Sure OAuth2 token is refreshed as needed

---

src/templates/kubernetes/skipper/skipper-deployment.yaml

- add volume mounts
This should have been in https://github.com/spring-cloud/spring-cloud-dataflow/pull/3907

Fix kubernetes template for skipper

---

spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/StepBeanDefinitionRegistrar.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationJobIncrementerTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationNoPropertiesTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesTests.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtilsTests.java

resolves #3919  
resolves #3921

Support commandLineArgs for specific apps in workflow

---

spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryPlatformTokenProvider.java
spring-cloud-dataflow-platform-cloudfoundry/src/test/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryPlatformPropertiesTests.java
spring-cloud-dataflow-platform-cloudfoundry/src/test/resources/application-cloudfoundry-platform-properties.yml

Configure CF platform connection client id

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Update ref docs for configMap and secret ref

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/features/TaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskConfigurationProperties.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTransactionTests.java

SCDF supports sending User OAuth token on CTR execution by default

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

Tasks launched by SCDF will now work if previously launched outside 

---

pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-test/pom.xml
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/core/dsl/tck/AbstractStreamDslTests.java
spring-cloud-dataflow-test/src/test/java/org/springframework/cloud/dataflow/core/dsl/tck/StreamDslTests.java

- Separate dsl tests into a different package so that those
can be used outside of a core dsl package.

Stream dsl tck tests

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/diff/TaskAnalyzer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/diff/TaskAnalyzerTests.java

Refactored AppDeploymentRequest creation. If the approach looks good, I will refactor the entire method.

GH-3610 Refactor DefaultTaskExecutionService's executeTask

---

spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformAutoConfiguration.java
spring-cloud-dataflow-platform-kubernetes/src/main/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformFactory.java
spring-cloud-dataflow-platform-kubernetes/src/test/java/org/springframework/cloud/dataflow/server/config/kubernetes/KubernetesTaskPlatformFactoryTests.java

Copies platform deployer properties to schedule

---

pom.xml
src/kubernetes/skipper/skipper-deployment.yaml

Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/4038

Upgrade fabric8 kubernetes-client

---

spring-cloud-dataflow-configuration-metadata/src/main/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolver.java
spring-cloud-dataflow-configuration-metadata/src/test/java/org/springframework/cloud/dataflow/configuration/metadata/BootApplicationConfigurationMetadataResolverTests.java

- Retrieve inbound/outbound port mapping metadata from container image labels

Fix inbound/outbound port mapping metadata for container images

---

spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryPlatformProperties.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformFactory.java
spring-cloud-dataflow-platform-cloudfoundry/src/test/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformFactoryTests.java

Updated schedulerProperties for cf props to schedule

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc

Also updated property keys for schedules
resolves #3976

Added reference to dataflow.spring.io docs on multi-platform tasks

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc

Add docs about schema handling

---

spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-building.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-contributing.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-dataflow-template.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-howto.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-identity-provider-azure.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-identity-providers.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/appendix.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/applications.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/architecture.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-cloudfoundry.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-local.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/preface.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/samples.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/shell.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams-developer-guide.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams-monitoring.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/task-developer-guide.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks-monitoring.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Editing the Asciidoc files to catch up with recent changes.

Editing pass

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDefinitionsDocumentation.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/AppRegistrationResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java

- When retrieving AppRegistryResource(s) for a given stream, the app label needs to be set.
- Update documentation test
Resolves #4120

Update label for AppRegistryResource

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

- Add ROLE_VIEW authorization to this endpoint
Resolves #4130

Add streams/definitions/*/applications to auth endpoints

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerServiceTests.java

CTR now does not have to be registered to schedule composed tasks.

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobStepExecutionsDocumentation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskSaveService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Restrict stream creation if the stream name has underscore

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtils.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtilsTests.java

resolves #4128
url can also be overridden using properties.

Users can override driverClassName property

---

spring-cloud-dataflow-server/docker-compose.yml
spring-cloud-dataflow-server/pom.xml

Change to 11.0.8 base image

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobServiceTests.java

resolves #4216
https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/359 must be merged first.

Job Props inserted by batch will now have type added on restart.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcDataflowJobExecutionDao.java

Fix deletion of batch job instances when cleaning up task executions

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcDataflowJobExecutionDao.java

- Regression for #4234 due to wrong sql
- Fixes #4244

Fix wrong sql for task execution cleanup

---

src/grafana/prometheus/docker/grafana/dashboards/scdf-kafka-streams.json

Add Kafka Streams Prometheus dashboard

---

spring-cloud-dataflow-platform-kubernetes/pom.xml

- Change from spring-cloud-starter-kubernetes-config
to spring-cloud-starter-kubernetes-client-config.
- Fixes #4301

Fix k8s config starter

---

spring-cloud-dataflow-composed-task-runner/pom.xml

No longer needed
resolves #4308

Removed mockito-core from CTR dependencies

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/assembler/DefaultTaskDefinitionAssembler.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

Fixes gh-4297 (#4297)

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc

Replaced scheduler. prefix with deployer. for scheduler deployer props

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

Reference :https://github.com/spring-cloud/spring-cloud-dataflow/issues/4272

fix issue-4272-Updated composed task runner uri

---

spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests-install.yml

https://github.com/spring-cloud/spring-cloud-dataflow/pull/4337/files

Fixed test that is failing because of the following commit.

---

spring-cloud-dataflow-composed-task-runner/pom.xml

Updated to remove SCDF-Core from CTR build

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java

Resolves parse error when property contains embedded `|`

---

spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc
spring-cloud-dataflow-server/README.adoc
spring-cloud-dataflow-server/docker-compose-dood.yml
spring-cloud-dataflow-server/docker-compose-rabbitmq.yml
spring-cloud-dataflow-server/docker-compose.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java

Set stream app URI shortcuts to Einstein

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/resources/my_http_analytics_total.json

- In DataFlowIT fix the actuator/logfile for Boot 2.3.x
- rename the counter to analytics sink.
Resolves #4350 for 2.8.x

Fix IT tests for new streaming applications

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AppRegistryController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/InvalidApplicationNameException.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java

Fixes #4196
- Added new custom exception InvalidApplicationNameException
- added copyright

Added new custom exception InvalidApplicationNameException

---

pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowServerConfiguration.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TaskServiceDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java

Also creeated new PlatformTransactionManager Bean to work around Task's introduction of springCloudTaskTransactionManager.
reesolves #4375

Updated task dependency to 2.3.0.

---

spring-cloud-dataflow-composed-task-runner/pom.xml

CTR docker image now has a label that contains the viewable properties for CTR .
resolves 4405

CTR meta props will now work for docker images.

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/resources/docker-compose-docker-it-task-import.yml
spring-cloud-dataflow-server/src/test/resources/docker-compose-maven-it-task-import.yml
spring-cloud-dataflow-server/src/test/resources/task_metrics_system_cpu_usage.json

Add Task metrics integration tests.

Add task metrics (prometheus) IT

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
src/templates/docker-compose/docker-compose-dood.yml
src/templates/docker-compose/docker-compose-rabbitmq.yml
src/templates/docker-compose/docker-compose.yml

Add an IT/AT test that deploys http (3.x) + log (3.x) stream, then updates it to http (3.x) + log (2.x) stream and finally rollback  to http (3.x) + ver-log (3.x) stream.

App cross version it at test

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java
spring-cloud-dataflow-server/src/test/resources/my_http_analytics_total.json

- Split analytic test in two dedicated Prometheus and Influx tests rather then using multiple if/thens

Streamline IT/AT tests

---

pom.xml
spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/DockerComposeFactory.java

- Switch to use our own cleaned fork in IT tests.
- Fixes #4465

Remove palantir repo

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server/src/test/resources/docker-compose-docker-it-task-import.yml
spring-cloud-dataflow-server/src/test/resources/docker-compose-maven-it-task-import.yml
src/docker-compose/docker-compose-dood.yml
src/docker-compose/docker-compose-rabbitmq.yml
src/docker-compose/docker-compose-ssl.yml
src/docker-compose/docker-compose.yml
src/templates/docker-compose/docker-compose-dood.yml
src/templates/docker-compose/docker-compose-rabbitmq.yml
src/templates/docker-compose/docker-compose-ssl.yml
src/templates/docker-compose/docker-compose.yml

```
export DATAFLOW_URI=https://dataflow-server:9393
export SKIPPER_URI=https://skipper-server:7577
docker-compose -f ./src/docker-compose/docker-compose.yml -f ./src/docker-compose/docker-compose-ssl.yml up
```

Config HTTPS for SCDF/Skipper and OOTB apps

---

src/docker-compose/docker-compose-dood.yml
src/docker-compose/docker-compose-postgres.yml
src/docker-compose/docker-compose.yml
src/templates/docker-compose/docker-compose-dood.yml
src/templates/docker-compose/docker-compose-postgres.yml
src/templates/docker-compose/docker-compose.yml

- Try not to override entrypoint where possible
- Rely on restart policy
- Relates #4493

Align docker compose with cloud native images

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc

Improves the documentation of deploymentServiceAccountName. (https://github.com/spring-cloud/spring-cloud-dataflow/issues/4488)

Adjusted deploymentServiceAccountName documentation

---

pom.xml
spring-cloud-dataflow-core/pom.xml
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/DefaultStreamDefinitionService.java
spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/TaskDefinitionToDslConverter.java
spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/dsl/StreamDslTests.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/AppStatusResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskSchedulerController.java
spring-cloud-dataflow-shell-core/pom.xml

- Remove commons-lang
- Remove commons-text dep handling
- Migrage to spring StringUtils and handle other deprecations
- Fixes #4519

Remove commons-lang

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

- Replace the wildcard with an explicit list of apps to be configured with LB.
- Ensure that all http source apps and apps that need to provide actuator/logfile access are configured with LB.
Resolves #4499

Enable K8s-LB only for externally accessible apps

---

spring-cloud-dataflow-server/README.adoc
spring-cloud-dataflow-server/pom.xml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/IntegrationTestProperties.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractDataflowTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/MssqlSeparateDbIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/MssqlSharedDbIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/container/DataflowCluster.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/tags/Mssql.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/tags/TagNames.java

Mssql db integration tests

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTasklet.java
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/support/ComposedTaskException.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTaskletTests.java

Add a better exception message on invalid task config.

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc

Document K8s additionalContainers feature

---

src/docker-compose/docker-compose-zipkin.yml
src/templates/docker-compose/docker-compose-zipkin.yml

Add docker-compose to configure  Zipkin Server

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

CF task execs are allowed if previous exec did not record external exec id

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/dsl/task/Task.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

Add batch based tests to IT/AT tests

---

spring-cloud-dataflow-container-registry/src/test/java/org/springframework/cloud/dataflow/container/registry/ContainerImageParserTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtilsTests.java

Co-authored-by: Moderne <team@moderne.io>
Not a big deal, but hope it helps :)

polish: statically import JUnit Jupiter assertions

---

spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedRunnerVisitorTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesNoLabelTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesWithLabelTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerStepFactoryTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskStepExecutionListenerTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTaskletTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskPropertiesTests.java
spring-cloud-dataflow-configuration-metadata/src/test/java/org/springframework/cloud/dataflow/container/registry/authorization/DockerConfigJsonSecretToRegistryConfigurationConverterTest.java
spring-cloud-dataflow-container-registry/src/test/java/org/springframework/cloud/dataflow/container/registry/authorization/DockerConfigJsonSecretToContainerRegistryConfigurationConverterTest.java

@jvalkeal Since you mentioned you were trying to get to AssertJ in #4610, hope this helps.
Co-authored-by: Moderne <team@moderne.io>

refactor: Migrate JUnit asserts to AssertJ

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

Tests updated to handle invalid data

---

spring-cloud-dataflow-single-step-batch-job/pom.xml
spring-cloud-dataflow-single-step-batch-job/src/main/resources/META-INF/dataflow-configuration-metadata-whitelist.properties
spring-cloud-dataflow-single-step-batch-job/src/main/resources/META-INF/dataflow-configuration-metadata.properties

The original pass only included the  properties for the readers and writers, not the suppporting spring props
resolves #4654

Added additional metadata filters for single step job app

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

Add dataflowTaskLauncherSink IT test

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
src/docker-compose/docker-compose-dood.yml
src/docker-compose/docker-compose-rabbitmq.yml
src/docker-compose/docker-compose.yml
src/templates/docker-compose/docker-compose-debug-dataflow.yml
src/templates/docker-compose/docker-compose-debug-skipper.yml
src/templates/docker-compose/docker-compose-dood.yml
src/templates/docker-compose/docker-compose-rabbitmq.yml
src/templates/docker-compose/docker-compose.yml

- Move the tasklaunncher app registration out of the IT test into the platform provisioning configs. (docker-compose files for IT and installation configs for K8s, CF)
- Make the test conditional on the dataflow-tasklaunncher is pre-registered.

Fix tasklauncher it

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedRunnerJobFactory.java
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskProperties.java
spring-cloud-dataflow-composed-task-runner/src/main/resources/META-INF/spring-configuration-metadata.json
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedRunnerVisitorTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskPropertiesTests.java
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Replacing runtimeIncrementer with ctr specific incrementer

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Removed customized CTR section in the docs

---

spring-cloud-dataflow-single-step-batch-job/src/main/resources/META-INF/dataflow-configuration-option-groups.properties

Replaced camel case with kabob case in option groups.

---

spring-cloud-dataflow-single-step-batch-job/src/main/resources/META-INF/dataflow-configuration-option-groups.properties

Removed dups
Re-added exhange to the reader.
resolves #4698

Updated options-group for SSBJ

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

Added acceptance tests for task versioning

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/dsl/task/Task.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

Add Acceptance Tests for Task Exec deletion

---

src/docker-compose/docker-compose-dood.yml
src/docker-compose/docker-compose-postgres.yml
src/docker-compose/docker-compose.yml
src/templates/docker-compose/docker-compose-dood.yml
src/templates/docker-compose/docker-compose-postgres.yml
src/templates/docker-compose/docker-compose.yml

Related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/4759

docker-compose: switch mysql to mariadb

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Added a delete for task_task_batch.
resolves #4785

Updated cleanup for platform task tests

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java

Backport #4785 
Resolves #4788

Updated cleanup for platform task tests - backport(4785)

---

spring-cloud-dataflow-composed-task-runner/README.adoc
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskStepExecutionListener.java
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTasklet.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/TaskLauncherTaskletTests.java
spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc

Adding support for ignoreExitMessage

---

spring-cloud-dataflow-classic-docs/pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/H2ServerConfigurationTests.java

Fix the full build issues caused by [PR 4806](https://github.com/spring-cloud/spring-cloud-dataflow/pull/4806)

fix: h2 issues on full build

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-rest-resource/src/test/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtilsTests.java

Updated arg parser to find all embedded quotes.

---

pom.xml

~⚠️ **DO NOT MERGE YET:** Depends on https://github.com/spring-cloud/spring-cloud-dataflow-build/pull/65/files~

Use managed spring-shell dependency from spring-cloud-dataflow-build

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/BaseDocumentation.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/MockUtils.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/StreamCommandTests.java

- Safe cleanup on task execution
- Deployer.<init> signature change for ActuatorOperations

Fix DataFlowIT issues w/ latest commits

---

spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerRegistryService.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/support/jackson/JobParameterJacksonDeserializer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/assembler/DefaultTaskDefinitionAssembler.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/LauncherInitializationService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AppDeploymentRequestCreator.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskDeleteService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java

This PR is the later version of https://github.com/spring-cloud/spring-cloud-dataflow/pull/4719 as it got wonky during merge/conflict.

Remove String.format from SL4J log statements

---

README.md

Archived repositories that are confusing

Remove old repositories links

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowOperationsITConfiguration.java
spring-cloud-dataflow-server/src/test/resources/docker-compose-docker-it-task-import.yml
spring-cloud-dataflow-server/src/test/resources/docker-compose-maven-it-task-import.yml
src/docker-compose/docker-compose.yml
src/local/README.md
src/local/create-containers.sh
src/local/simple-integration-test.sh
src/templates/docker-compose/docker-compose.yml

Improved exception handling and reporting in test setup.
fixed bin/sh in compose files.
added local developer support scripts.
Update baseImage to 1.0.1

Improve exception handling and logging in Integration test setup.

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java

@jvalkeal @corneil 
Lets see if this straightens things out

Fix DataFlowIT timestamp-task coordinates

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/AwaitUtils.java

Moved to AwaitUtils as static.

Refactor has error in log

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/AwaitUtils.java

Added `AwaitUtils.hasInLog` and `AwaitUtils.hasRegexInLog`

Add await regex in log

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/AwaitUtils.java

Added `StreamLog` to track the offset read so that old error messages don't cause failures

Refactor await utils

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/AwaitUtils.java

Ensure offset remains > 0 and not larger than log.

Improve await utils null checks

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AppDeploymentRequestCreator.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
src/docker-compose/docker-compose.yml
src/kubernetes/server/server-deployment.yaml
src/kubernetes/skipper/skipper-deployment.yaml
src/templates/kubernetes/server/server-deployment.yaml
src/templates/kubernetes/skipper/skipper-deployment.yaml

* Docker compose dependency on rabbit.
* k8s deployment will use busybox:1 with IfNotPresent.

Deployer logging

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeTemplate.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AboutController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppInstanceController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/security/SecurityController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/RootControllerTests.java
spring-cloud-dataflow-server-core/src/test/resources/root-controller-result.json
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DataFlowIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

Provide for HTTP POST to app with url.
fixes - https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/346

http POST endpoint

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/assembler/DefaultTaskDefinitionAssembler.java

Do not execute SQL to load manifest when parameter is 'false'.
Fixes https://github.com/pivotal/scdf-pro/issues/123

Respect 'manifest' task def controller parameter

---

spring-cloud-dataflow-docs/src/main/asciidoc/dashboard.adoc

It now contains definitions for the attributes of the metrics that are captured.
Also adds defintions for the metrics themselvess

Updated Step History section of the reference documentation.

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/ArgumentSanitizerTest.java
spring-cloud-dataflow-server-core/src/test/resources/sanitizer1.json
spring-cloud-dataflow-server-core/src/test/resources/sanitizer2.yaml

Add sanitizer to history output.

---

.editorconfig
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeTemplate.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppInstanceController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

Added retries to wait for URL to be available because of delay in DNS.

Improved ArgumentSanitizer

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDeploymentController.java

Backport sanitizer

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/RuntimeTemplate.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/util/RuntimeApplicationHelper.java

Ensure POST from Test application uses post link and POST in dataflow uses pod.ip.

Fix POST from Test application

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/DataFlowConfiguration.java
spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskProperties.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/properties/ComposedTaskPropertiesTests.java

feat: CTR client authentication method property

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceUpdateTests.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/support/YmlUtils.java

Use SafeConstuctor with SnakeYaml

---

spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-server-core/pom.xml

Fixes #5057
cc: @cppwfs @corneil @jvalkeal @markpollack

Remove Oracle and DB2 drivers

---

spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc

👍 😃 
resolves: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4863

doc: Include new team members

---

pom.xml

Added dataflow.version to parent pom

---

spring-cloud-dataflow-docs/src/main/asciidoc/tasks.adoc
spring-cloud-dataflow-tasklauncher/README.adoc

* Added readme for task launcher
* Updated instructions for launching CTR for streams
Resolves #4869

Updating and adding documentation for the Task Launcher

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java

Add a constructor that takes RestTemplate instead of field injection

---

src/carvel/config/dataflow-deployment.yml
src/carvel/config/dataflow.star
src/carvel/config/skipper-deployment.yml
src/carvel/config/skipper.star
src/carvel/config/values/values.yml

Updated carvel values schema and configuration for override hibernate dialect in values which will add an environmental variable.

Provide for overriding the dialect.

---

src/carvel/config/dataflow-deployment.yml
src/carvel/config/dataflow.star
src/carvel/config/skipper-deployment.yml
src/carvel/config/skipper.star
src/carvel/config/values/values.yml
src/carvel/test/servers.test.ts

Remove check for default limits.

Provide for overriding dialect.

---

src/local/README.md
src/local/create-containers.sh
src/local/download-apps.sh

The download-apps.sh script will provide for downloading the jar packages for all the application used in create-containers.sh

Add download-apps.sh

---

src/docker-compose/docker-compose-dood.yml
src/local/create-containers.sh
src/local/download-apps.sh

Updated docker-compose with 'sh' commands.

Updated download-apps.sh and create-containers.sh.

---

src/carvel/config/dataflow.star
src/carvel/config/skipper.star
src/kubernetes/server/server-deployment.yaml
src/kubernetes/skipper/skipper-deployment.yaml

Provide environmental variable `LANG=en_US.UTF-8` and `LC_ALL=en_US.UTF-8` by default.

Provide environmental variable LANG

---

src/carvel/config/dataflow-deployment.yml
src/carvel/config/skipper-deployment.yml
src/kubernetes/server/server-deployment.yaml
src/kubernetes/server/server-svc.yaml
src/kubernetes/skipper/skipper-deployment.yaml
src/templates/kubernetes/server/server-deployment.yaml
src/templates/kubernetes/server/server-svc.yaml
src/templates/kubernetes/skipper/skipper-deployment.yaml

Ensure dataflow server and skipper uses ports above 1024 in pods

---

spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/authorization/DockerConfigJsonSecretToRegistryConfigurationConverter.java
spring-cloud-dataflow-container-registry/src/test/java/org/springframework/cloud/dataflow/container/registry/authorization/DockerConfigJsonSecretToContainerRegistryConfigurationConverterTest.java

Colon (port) in docker registry URI cause error

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/StreamService.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceTests.java

Add deploy props param to "create stream" REST API

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-database.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-local.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-kubernetes.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/getting-started-local.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/index.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/overview.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/preface.adoc

This updates the 1st half of the ref doc - more PRs to come. 
See #4807
cc: @corneil

Ensure ref doc is up-to-date and valid

---

spring-cloud-dataflow-server-core/src/main/resources/META-INF/spring.factories
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/config/FlywayVendorReplacingApplicationContextInitializerTests.java

Depends on https://github.com/spring-cloud/spring-cloud-dataflow-common/pull/24
Fixes #5164

Convert Flyway vendor replacer from EPP to ACI

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractDataflowTests.java

Change from `springsource-docker-private-local.jfrog.io` to `dev.registry.pivotal.io/p-scdf-for-kubernetes`

Change private repositories

---

.github/settings.xml
.settings.xml
pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-server/pom.xml

See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193

Add MavenCentral in place of repo.spring.io/release

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/job/StepExecutionHistory.java

Removed invalid deprecation on StepExecutionHistory.getReadCount

---

src/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml
src/local/k8s/delete-scdf.sh
src/templates/kubernetes/prometheus-proxy/prometheus-proxy-deployment.yaml

Script now removes cluster roles, cluster role bindings, and service account for prometheus if user sets PROMETHEUS to true. Updated proxy to 1.5 from 0.11.0

Updated version for prometheus proxy and updated delete script

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-extend-classpath.adoc

Update the `extend classpath` section of ref docs.

---

spring-cloud-dataflow-docs/src/main/asciidoc/appendix-local-k8s-development.adoc

Updated ref docs for local k8s/use-*.sh scripts.

Updated docs on `k8s/use-*.sh` scripts.

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes-app-properties.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc

Documents the changes made in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/525
See #5163

Update k8s pod and container security context docs.

---

.github/workflows/carvel-worker.yml
.github/workflows/ci-carvel.yml
.gitignore

Make env vars explicit.

---

.github/settings.xml
.github/workflows/ci-pr.yml
.settings.xml
pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-server/pom.xml
src/local/download-apps.sh

Fix CI-PR build to use .github/settings.xml since it isn't using JFrog cli.

Fix CI-PR build

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDefinitionsDocumentation.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommands.java
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/converter/AppBootSchemaVersionConverter.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/AbstractShellIntegrationTest.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommandsTests.java

- Create AppRegistryCommandsTests that verify newly added bootVersion options
See #5239

Add tests for shell 'app register' commands

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
.github/workflows/milestone-worker.yml
.github/workflows/next-dev-version-worker.yml
.github/workflows/release-worker.yml
src/docker-compose/dc.sh
src/docker-compose/docker-compose-kafka.yml
src/docker-compose/docker-compose.yml

Added Maven Threading to builds.

Added Maven Threads, update docker-compose and dc.sh

---

spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker-junit5/src/test/java/org/springframework/cloud/dataflow/common/test/docker/junit5/DockerCompose3Tests.java

Currently this test will fail.   With this update it matches the other tests.

Docker test will ignore case.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/AbstractBootVersionMigration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/db2/V7_Boot3_Boot_Version.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mariadb/V7_Boot3_Boot_Version.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mysql/V7_Boot3_Boot_Version.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/oracle/V7_Boot3_Boot_Version.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/postgresql/V7_Boot3_Boot_Version.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/sqlserver/V7_Boot3_Boot_Version.java
spring-cloud-dataflow-server/src/test/resources/application.properties

Added classes for Boot Schema version in app-registration.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java

Update TaskExecutionResource with link to tasks/logs

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java

Add tasks/logs to TaskExecutionResource

---

spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-rest-resource/pom.xml
spring-cloud-dataflow-single-step-batch-job/pom.xml

Update to jettison 1.5.2

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml

See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5308

Update Spring Boot 2.7.11

---

spring-cloud-dataflow-server-core/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml

Add hibernate-micrometer to enable Hibernate metrics

---

spring-cloud-dataflow-server-core/pom.xml

Backport "Add hibernate-micrometer to enable Hibernate metrics (#5322)"

---

.settings.xml
pom.xml
spring-cloud-dataflow-classic-docs/src/test/resources/rest-docs-config.yml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-docs/src/main/asciidoc/appendix-howto.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-cloudfoundry.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes-app-properties.adoc
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/AboutController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/TestDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AboutControllerTests.java
spring-cloud-dataflow-server/pom.xml
src/kubernetes/server/server-deployment.yaml
src/local/download-apps.sh
src/local/k8s/register-apps.sh
src/local/k8s/yaml/server-deployment-pro.yaml
src/local/k8s/yaml/server-deployment.yaml
src/templates/kubernetes/server/server-deployment.yaml

See spring-cloud/spring-cloud-dataflow#5325

Switch Maven repos off of libs-* variants

---

src/carvel/test/databases.test.ts
src/carvel/test/errors.test.ts
src/carvel/test/generic.test.ts
src/carvel/test/kafka.test.ts
src/carvel/test/rabbitmq.test.ts
src/carvel/test/secrets.test.ts
src/carvel/test/servers.test.ts

Update tests for carvel.

---

spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommands.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/AbstractShellIntegrationTest.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/ShellCommandsTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/AppRegistryCommandsTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/ConfigCommandTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/JobCommandTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/RuntimeCommandsTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/StreamCommandTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskCommandTests.java
spring-cloud-dataflow-shell-core/src/test/java/org/springframework/cloud/dataflow/shell/command/TaskScheduleCommandsTest.java
spring-cloud-dataflow-shell/pom.xml

- Update related tests to Junit5
See #5239

Add boot version to `app info` shell command

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/support/SpringDocJsonDecodeFilter.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/support/SpringDocJsonDecodeFilterTest.java

Also resolve issue if openai json is unescaped.  Test added to validate this case.
resolves #5281

Establish default for swagger-ui.url

---

spring-cloud-dataflow-docs/src/main/asciidoc/spring-boot-3x.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Add doc for Spring Boot 3

---

spring-cloud-dataflow-aggregate-task/src/main/java/org/springframework/cloud/dataflow/aggregate/task/AggregateExecutionSupport.java
spring-cloud-dataflow-schema-core/src/main/java/org/springframework/cloud/dataflow/schema/AggregateTaskExecution.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JobExecutionDaoContainer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JobRepositoryContainer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/JobExplorerContainer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/JobServiceContainer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AppRegistryControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobExecutionThinControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobStepExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/RootControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/RuntimeAppsControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TasksInfoControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/JdbcDataflowTaskExecutionDaoTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/TaskExecutionExplorerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskDeleteServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionServiceTransactionTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobServiceTests.java

* When an invalid schema is specified.
* Did some polishing

Now throws NoSuchSchemaTarget instead of NPE

---

spring-cloud-dataflow-parent/pom.xml

Resolves issue where task logs are not viewable.

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AboutDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/ApiDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AuditRecordsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobInstancesDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobStepExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/RuntimeAppsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/RuntimeStreamStatusForStreamAppsWithoutCollectorDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/SchemaDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDefinitionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDeploymentsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamLogsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamValidationDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskDefinitionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskLogsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskPlatformDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskSchedulerDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskValidationDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TasksInfoDocumentation.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/controller/support/SimpleResourceAssembler.java

suppress naming convention warnings for Rest Docs.

Fix documentation error.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/StreamControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployerTests.java

Skipper undeploy attempts delete of other info when no package is found for stream

---

spring-cloud-dataflow-docs/src/main/asciidoc/spring-boot-3x.adoc
spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc

Add coordinates for out-of-box task apps

---

spring-cloud-dataflow-docs/pom.xml

See https://github.com/spring-cloud/spring-cloud-dataflow/commit/1e64fe321048a157c103f7d3ea97d2a166f2a610#diff-bf62ae12f664c0a629ce9a6990e94e63ecbd5317f6342abfb43878992483598b.
Resolves #5430

Backport move to io.spring.asciidoctor.backends in docs module.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamService.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests.java
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests-deployManifest.yml
spring-cloud-dataflow-server-core/src/test/resources/org/springframework/cloud/dataflow/server/service/impl/DefaultStreamServiceIntegrationTests-install.yml

Hide sensitive data on update audit records.

---

spring-cloud-dataflow-aggregate-task/README.adoc

Section also discusses where to find tests
resolves #5446

Readme describes the spr-cloud-dataflow-aggregate-task module

---

spring-cloud-dataflow-server-core/src/main/resources/org/springframework/cloud/dataflow/server/db/migration/h2/V1__INITIAL_SETUP.sql

Increase AUDIT_RECORDS.AUDIT_DATA field for H2

---

spring-cloud-dataflow-core-dsl/src/main/java/org/springframework/cloud/dataflow/core/dsl/StreamParser.java

Readded param to method

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-shell-core/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server/pom.xml
spring-cloud-skipper/spring-cloud-skipper-shell-commands/pom.xml

* com.nimbusds:nimbus-jose-jwt:9.31
* net.minidev:json-smart:2.4.11
* org.xerial.snappy:snappy-java:1.1.10.4
* org.yaml:snakeyaml:1.33

Add versions to dependency management for CVEs

---

.github/workflows/milestone-worker.yml
.github/workflows/next-dev-version-worker.yml
.github/workflows/release-worker.yml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-dependencies-parent/pom.xml
spring-cloud-dataflow-common/spring-cloud-dataflow-common-dependencies/pom.xml
spring-cloud-dataflow-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-skipper/spring-cloud-skipper-dependencies/pom.xml

* Add common security modules to dependency management
* Replace use of project.version w/ dataflow.version
Fixes #5485

GH-5485: Add common security modules to dep. mgmt

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java

Update TaskTemplate.launch to provide backwards compatible behaviour

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/AppDeploymentRequestCreator.java

Provide for setting cloudfoundry deployer options for deploying Spring Boot 3 applications requiring JDK 17.

[Do Not Merge] Deploying Spring Boot 3 on Cloud Foundry 

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerStepFactory.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesWithLabelTests.java

Fix CTR duplicating properties with similar names.

---

README.md
spring-cloud-dataflow-common/spring-cloud-dataflow-common-flyway/pom.xml

* This was missed on the Spring Boot 2.7.17 update.
* Also updates snippet in README.md so users know how to build.
See #5522

Update Flyway to 8.5.13

---

.settings.xml
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryPlatformClientProvider.java
spring-cloud-dataflow-platform-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformFactory.java
spring-cloud-dataflow-platform-cloudfoundry/src/test/java/org/springframework/cloud/dataflow/server/config/cloudfoundry/CloudFoundryTaskPlatformFactoryTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/CloudFoundrySchedulerTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/single/MultiplePlatformTypeTests.java
spring-cloud-skipper/spring-cloud-skipper-autoconfigure/src/main/java/org/springframework/cloud/skipper/server/autoconfigure/CloudFoundryPlatformAutoConfiguration.java

This commit picks up the changes in Spring Cloud Deployer https://github.com/spring-cloud/spring-cloud-deployer/commit/a36ee24d898bd7bb8ddc7d254c3df535f4bcda93

Update CloudFoundry deployers to include ApplicationLogAccessor

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

Bump spring boot 2.17.18

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/JdbcSearchableJobExecutionDao.java

Fix use of table prefix.

---

spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/JobTemplate.java

Fix the HATEOAS reference.

---

.github/workflows/download-jar/build.gradle
.github/workflows/release-worker.yml

Use new private release repo libs-release-staging

---

src/docker-compose/dc.sh

Improve docker-compose script to handle docker compose and docker-compose.

---

src/docker-compose/docker-compose-dood.yml

Installation of docker was removed when wait-for-it was removed. Fixes #5582 [skip ci]

Fix docker-compose-dood.yml. 

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/DropColumnSqlCommands.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/db2/V9__DropJobConfigurationLocation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mariadb/V10__DropJobConfigurationLocation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/mysql/V10__DropJobConfigurationLocation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/oracle/V10__DropJobConfigurationLocation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/postgresql/V11__DropJobConfigurationLocation.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/sqlserver/V9__DropJobConfigurationLocation.java

Drop JOB_CONFIGURATION_LOCATION from batch tables.

---

spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/AuditRecordControllerTests.java

* Added another pause when setting up the data for the tests.
* Set the date tests to be a bit more robust to make sure that their data is present vs an absolute count check.

Date Tests need to handle delayed audit records

---

spring-cloud-dataflow-aggregate-task/src/test/resources/logback-test.xml
spring-cloud-dataflow-server-core/src/test/resources/logback-test.xml
spring-cloud-dataflow-server/src/test/resources/logback-test.xml
spring-cloud-skipper/spring-cloud-skipper-server/src/test/resources/logback-test.xml
spring-cloud-starter-dataflow-server/src/test/resources/logback-test.xml

The amount of test logging is preventing our test reports from uploading to Github.

Reduce test logging

---

src/deploy/images/pull-app-images.sh
src/deploy/k8s/deploy-scdf.sh
src/deploy/k8s/load-image.sh
src/deploy/k8s/load-images.sh
src/deploy/k8s/register-apps.sh
src/deploy/k8s/update-scdf.sh
src/local/launch-dataflow.sh
src/local/register-apps.sh

Update scripts for loading latest snapshots.

---

.editorconfig
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-skipper/spring-cloud-skipper-docs/src/main/asciidoc/appendix-building.adoc

Updated Spring cloud version and documentation.

---

README.md
spring-cloud-dataflow-server/pom.xml

**⚠️ READ THE WIKI BEFORE REVIEWING ⚠️** 
https://github.com/spring-cloud/spring-cloud-dataflow/wiki/MSSQL-on-Mac-ARM64

Add profile to run MSSQL locally

---

spring-cloud-dataflow-aggregate-task/src/main/java/org/springframework/cloud/dataflow/aggregate/task/impl/AggregateDataFlowTaskExecutionQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/TaskExecutionExplorerTests.java

Fixes #5615 and https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1948

Adding support for sorting by SchemaTarget.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/StreamDeployerUtil.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml

Improve logging for StreamDeployerUtil

Add role for POST runtime/apps/

---

create-carvel-package.sh
spring-cloud-dataflow-container-registry/src/test/java/org/springframework/cloud/dataflow/container/registry/ContainerImageParserTests.java
spring-cloud-dataflow-docs/src/main/asciidoc/configuration-carvel.adoc
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractDataflowTests.java
src/deploy/README.html
src/deploy/carvel/carvel-prepare-namespaces.sh
src/deploy/carvel/delete-scdf.sh
src/deploy/carvel/load-images.sh
src/deploy/carvel/prepare-local-namespace.sh
src/deploy/carvel/scdf-pro-values.yml
src/deploy/carvel/setup-scdf-repo.sh
src/deploy/images/pull-scdf-pro.sh
src/deploy/images/pull-skipper-pro.sh
src/deploy/k8s/deploy-scdf.sh
src/deploy/k8s/update-scdf.sh
src/deploy/k8s/yaml/server-deployment-pro.yaml
src/deploy/k8s/yaml/skipper-deployment-pro.yaml

[CI] Rename registry.pivotal.io to registry.tanzu.vmware.com. [skip-ci]

[CI] Rename registry.pivotal.io to registry.tanzu.vmware.com

---

src/deploy/carvel/scdf-oss-values.yml
src/deploy/carvel/scdf-pro-values.yml

Ensure the sample Carvel deployment provides UTF-8 as default encoding to containers.

Ensure the sample Carvel deployment provides UTF-8 as default encoding.

---

spring-cloud-dataflow-common/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/support/YmlUtils.java

Remove Dependency Management for 2.11.x CVE.

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-skipper/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/util/ConfigValueUtils.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/util/ManifestUtils.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/service/PackageServiceTests.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/templates/PackageTemplateTests.java

**DNSDM** = `DO NOT SQUASH DURING MERGE`
The commits have been done dependency / commit in order to have better visibility into activity.

⚠️ DNSDM ⚠️ (see below) update/cleanup various dependency overrides / management

---

spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/resources/application.yml

This is a same fix for skipper server done in #5670 for dataflow server.

Config client legacy processing

---

pom.xml
spring-cloud-dataflow-audit/pom.xml
spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-tools/pom.xml
spring-cloud-dataflow-configuration-metadata/pom.xml
spring-cloud-dataflow-container-registry/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-platform-kubernetes/pom.xml
spring-cloud-dataflow-rest-client/pom.xml
spring-cloud-dataflow-rest-resource/pom.xml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/DataflowSqlPagingQueryProvider.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/JdbcSearchableJobExecutionDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/AggregateDataFlowTaskConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/JobExplorerContainer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/batch/AbstractSimpleJobServiceTests.java
spring-cloud-dataflow-shell/pom.xml
spring-cloud-skipper/pom.xml
spring-cloud-skipper/spring-cloud-skipper-platform-cloudfoundry/pom.xml
spring-cloud-skipper/spring-cloud-skipper/pom.xml
spring-cloud-starter-dataflow-server/pom.xml

This will facilitate Dataflow to start
* Made sure JobExplorer has access to PlatformTransactionManager since it is no longer provided by batch
* WARNING I put a `@Primary` runtimeAppsStatusFJPFB for to resolve mulitple bean error.  This looks right, but I can be wrong!!!

Stub out DataflowPagingProviders so that beans can be created

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-carvel.adoc
src/carvel/config/skipper.star
src/carvel/test/servers.test.ts
src/deploy/carvel/add-local-registry-secret.sh
src/deploy/carvel/carvel-add-registry-secret.sh
src/deploy/carvel/carvel-import-secret.sh
src/deploy/carvel/carvel-prepare-namespaces.sh
src/deploy/carvel/deploy-local-broker.sh
src/deploy/carvel/deploy-local-database.sh
src/deploy/carvel/deploy-scdf.sh
src/deploy/carvel/prepare-cluster.sh
src/deploy/carvel/prepare-local-namespace.sh
src/deploy/carvel/scdf-oss-values.yml
src/deploy/carvel/scdf-pro-values.yml
src/deploy/carvel/setup-scdf-repo.sh
src/deploy/k8s/configure-k8s.sh
src/deploy/versions.yaml

Update to Carvel Packaging and deployment scripts. [skip ci]

[CI] Update Carvel packaging and deployment scripts. 

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/ci-it-db.yml
.github/workflows/ci-it-security.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml

Updated docker/login-action to v3

Added DockerHub login to CI to prevent failure of TestContainer tests.

---

.github/workflows/ci-pr.yml
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/arm64/Db2Arm64ContainerSupport.java
spring-cloud-dataflow-test/src/main/java/org/springframework/cloud/dataflow/server/db/arm64/OracleArm64ContainerSupport.java

add container logging

---

spring-cloud-skipper/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachineConfiguration.java
spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine/StateMachinePersistConfiguration.java

This should make skipper to start and run. Simple ticktock stream should work ok.
There's small changes to fix changes in sm api's.

Upgrade spring-statemachine 4.0.0

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-skipper/pom.xml

commons compress update

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-docs/pom.xml
spring-cloud-dataflow-parent/pom.xml

* Bump PostgreSQL Driver version to 42.7.2 [CVE-2024-1597](https://avd.aquasec.com/nvd/2024/cve-2024-1597)
* Bump Spring Framework version to 5.3.32 [CVE-2024-22243](https://avd.aquasec.com/nvd/cve-2024-22243)

Bump PostgreSQL Driver version to 42.7.2

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/ci-it-db.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractDatabaseTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/AbstractDataflowTests.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/OracleSeparateDbIT.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/db/container/DataflowCluster.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/tags/TagNames.java

Adding TestContainers Cloud.
Improve method names as same it used for separate and shared configurations.
Change to same Oracle as other integration tests.

adding test containers cloud

---

spring-cloud-dataflow-aggregate-task/src/main/java/org/springframework/cloud/dataflow/aggregate/task/impl/AggregateDataFlowTaskExecutionQueryDao.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/ApiDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskOperations.java
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskExecutionThinResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/DataFlowControllerAutoConfiguration.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionThinController.java
spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/configuration/JobDependencies.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java

Adding Thin Task Executions Controller to improve task list / paging performance.
Fixes #5718

Thin task execution controller

---

spring-cloud-dataflow-docs/src/main/asciidoc/configuration-kubernetes.adoc

update k8s docs

---

src/deploy/k8s/yaml/server-config.yaml
src/deploy/k8s/yaml/server-deployment.yaml
src/deploy/k8s/yaml/skipper-config-kafka.yaml
src/deploy/k8s/yaml/skipper-config-rabbit.yaml
src/deploy/k8s/yaml/skipper-deployment.yaml

Used by local k8s deployment scripts.

[CI] Improve k8s limits.

---

spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskExecutionThinResource.java

The synthesized method did not make it into the TaskExecutionThinResource.
There will be an issue with CTR tasks. We need to determine update the new thin query to collect the CTR status.

Added taskExecutionStatus to TaskExecutionThinResource.

---

pom.xml
spring-cloud-common-security-config/pom.xml
spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-skipper/pom.xml

Update Spring Security to 5.7.12
Update Spring Shell to 2.1.15
Only known snake-yaml and spring-web remain.

Update Spring Framework to 5.3.34

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/ApiDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobInstancesDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobStepExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDefinitionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskDefinitionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskSchedulerDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/resources/rest-docs-config.yml
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/impl/DefaultDataFlowTaskExecutionQueryDao.java

Remove documentation for boot version and schemaTarget.
Update for newer version of rest docs.

fix documentation for boot 3.x

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

Update Nimbus to 9.37.2 for CVE-2023-52428

---

spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-parent/pom.xml

Addresses the following CVEs:
- https://github.com/advisories/GHSA-v682-8vv8-vpwr
- https://github.com/advisories/GHSA-7w75-32cg-r6g2
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5780

Update Tomcat embedded to 9.0.88

---

.github/workflows/ci-it-db.yml
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/tasks/TaskExecutionQueryContainer.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/DB2_11_5_SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/support/DatabaseTypeTests.java
spring-cloud-skipper/spring-cloud-skipper-server/src/test/java/org/springframework/cloud/skipper/server/db/migration/DB2_11_5_SkipperSmokeTest.java

Add job to integration test to explicitly test with DB2.

Disabling DB2 tests by default.

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/ci.yml
.github/workflows/milestone-worker.yml
.github/workflows/release-worker.yml

Change error handling for skipper-docs-name to ensure error messages surface.

Change error handling for skipper-docs-name

---

spring-cloud-skipper/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/PackageService.java

Improves `validateUploadRequest` and applies it after tmp directory is created.

Improved validateUploadRequest in PackageService

---

spring-cloud-dataflow-aggregate-task/pom.xml

Update scope of spring-boot-starter-test for spring-cloud-dataflow-aggregate-task.

Update scope of spring-boot-starter-test

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
spring-cloud-dataflow-common/spring-cloud-dataflow-common-flyway/pom.xml
spring-cloud-dataflow-common/spring-cloud-dataflow-common-flyway/src/main/java/org/flywaydb/database/mysql/MySQL57Database.java
spring-cloud-dataflow-composed-task-runner/pom.xml
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java
spring-cloud-dataflow-server-core/pom.xml
spring-cloud-dataflow-shell-core/src/main/java/org/springframework/cloud/dataflow/shell/command/ConfigCommands.java
spring-cloud-dataflow-single-step-batch-job/pom.xml
spring-cloud-dataflow-tasklauncher/spring-cloud-dataflow-tasklauncher-sink-dependencies/pom.xml
spring-cloud-dataflow-tasklauncher/spring-cloud-dataflow-tasklauncher-sink-kafka/pom.xml
spring-cloud-dataflow-tasklauncher/spring-cloud-dataflow-tasklauncher-sink-rabbit/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml

* Update version of the apps metadata plugin used by the sample apps to get around issue of NoClassDefFound for spring-data-jdbc config props
* Modify MySQL57Database to use newly introduced `ensureSupported` API
* Replace use of `OAuth2ClientPropertiesRegistrationAdapter` with newly introduced `OAuth2ClientPropertiesMapper`

Update to Spring Boot 3.3.0 [DO NOT SQUASH]

---

spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfiguration.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationNoPropertiesTests.java
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithPropertiesTests.java

CTR needs to support boot property styles for the tablePrefix property

---

spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/main/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DockerComposeExecutable.java

Ensure docker-compose uses docker compose when docker-compose executable is absent.
Fixes #5890

Handle case where docker-compose executable is absent.

---

spring-cloud-dataflow-core/src/main/java/org/springframework/cloud/dataflow/core/ThinTaskExecution.java
spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/resource/TaskExecutionThinResource.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionThinController.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/DataflowTaskExecutionQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/DataflowTaskExplorer.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/impl/DefaultDataFlowTaskExecutionQueryDao.java
spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/task/impl/DefaultDataflowTaskExplorer.java
spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionControllerTests.java

Added ThinTaskExecution to store ctrStatus.
Update Controller and Service to populate the ctr status.

Forward port ctr status on Thin Controller.

---

.github/workflows/build-snapshot-worker.yml
.github/workflows/ci-pr.yml
.github/workflows/ci.yml
.github/workflows/milestone-worker.yml
.github/workflows/publish-docs.yml
.github/workflows/release-worker.yml
spring-cloud-skipper/spring-cloud-skipper-docs/pom.xml
spring-cloud-skipper/spring-cloud-skipper-server-core/pom.xml
src/scripts/build-docs.sh

Remove actions that don't add value. 
Ensure documentation tests are executed.

[CI] Remove actions that don't add value. 

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/SqlServer_2017_SmokeTest.java
spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/support/DatabaseTypeTests.java

Disable failing SqlServer 2017 tests

---

spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithVersionPropertiesTests.java

Remove @Disabled from ComposedTaskRunnerConfigurationWithVersionPropertiesTests.composedConfiguration

Remove Disabled annotation from CTR Test

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-composed-task-runner/src/test/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerConfigurationWithVersionPropertiesTests.java
spring-cloud-dataflow-parent/pom.xml
spring-cloud-dataflow-server/pom.xml

Replace the hardcoded version with a property in each dependency, Set the property in the spring-cloud-dataflow parent
You will also notice I removed a unused import in a test.   Can remove if it needs to be put in another PR

Update maven-surefire-report-plugin to 3.5.0

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AppRegistryDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/AuditRecordsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobInstancesDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/JobStepExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDefinitionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamDeploymentsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/StreamValidationDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskDefinitionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskLogsDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskPlatformDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskSchedulerDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskValidationDocumentation.java
spring-cloud-dataflow-classic-docs/src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc
spring-cloud-skipper/spring-cloud-skipper-server-core/src/test/java/org/springframework/cloud/skipper/server/controller/docs/BaseDocumentation.java

Update request-parameters to query-parameters
Added optional where applicable
Added snippet template to query-parameters and updated template for path-parameters to improve readability.
Fixes #6008

Fix rest documentation for changes to spring-rest-docs

---

spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskDefinitionsDocumentation.java

Fixes failing builds on outstanding PR #6007 and merged PR #6012

Fix error after merge of task definition controller changes.

---

spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/batch/SimpleJobService.java

This can be removed because SCDF does not manage internal jobs, but rather launches boot apps that use Spring Batch
resolves #6034

Remove DisposableBean implements from SimpleJobService

---

spring-cloud-skipper/spring-cloud-skipper-docs/pom.xml

This is a non standard document type for the SCDF project.
Resolves #6025

Remove pdf doc generation for Spring Cloud Skipper

---

spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/test/java/org/springframework/cloud/dataflow/common/test/docker/compose/logging/LogDirectoryTest.java

This code was removed in the 2.11.x line.

Remove commented out code.

---

spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/oauth/DataflowOAuthIT.java

Added a negative test to DataflowOAuthIT to ensure /about cannot be accessed without credentials.

Added a negative test to DataflowOAuthIT

---

spring-cloud-dataflow-build/pom.xml
spring-cloud-dataflow-parent/pom.xml

Spring Boot 3.3.7
Spring Cloud Task 3.1.3
Fixes #6093

Update Spring Component Versions
